chore: Update lint:text command forincoming document
reactjs/ja.react.dev pull request #454
Opened 2021-12-02 03:50 UTC by noyanyan

This PR is a part of #453.

# 概要
Textlintを実行する`lint:text`コマンドがbeta/src/pagesフォルダもlintするよう変更しました。
また、以下の変更を加えました。
- globパターンをvalidに
- cacheの有効化

MDX対応は行いませんでした。これは新ドキュメントの拡張子もすべて`.md`で必要なかったためです。
### note:
[textlint-plugin-markdownで`.mdx`拡張子をlintすることは可能です](https://github.com/textlint/textlint/blob/d4c5075b5a7bcbf875d7cee122de7dc5253d325e/packages/%40textlint/textlint-plugin-markdown/README.md#options)が、これは.mdと同じ方法でlintしているだけです。また、textlintのmdxルールセットは見つかりませんでした。

# globパターンをvalidに
lintされていないディレクトリが存在したため(content/home/{examples, marketing})、これを修正しました。

TextLintではglobパターンを引用符で囲わなかった場合、Textlintはサブディレクトリの探索を行いません。
e.g. `yarn textlint src/**/*.md` は `src/page/1.md`を無視する

修正方法は[textlintのindex.md](https://github.com/textlint/textlint#cli)に従いました。
> When running texlint, you can target files to lint using the glob patterns. Make sure that you enclose any glob parameter you pass in quotes.

# cacheの有効化
lint対象が増えtextlintの処理時間が長くなることが予想されたので、--cacheオプションを有効化し高速化しました。自分の環境では12.8s => 2.3sと5.5倍高速化されています。

### Without Cache
![image](https://user-images.githubusercontent.com/63000297/144352327-d942f84d-3616-4853-b1ad-8185430efbc8.png)

### With Cache
![image](https://user-images.githubusercontent.com/63000297/144352050-2ba0a47a-e05f-4230-a9e5-4ff9229ea96a.png)

2021-12-02 03:57 UTC, noyanyan commented
動作の確認として以下の事項をテストし、問題がないことを確認しました。
- 更新した`lint:text`で`beta/src/pages`とそのサブディレクトリがlintされること、
- エラーを出したファイルをlint対象外のフォルダに移すとエラーが検出されなくなること
- 既存のwarningの数、メッセージが変更されないこと

2021-12-02 04:49 UTC, smikitky commented
beta ディレクトリの中はリポジトリのトップレベルとは独立した package.json や yarn.lock を持つ別環境であり、beta ディレクトリの中と外の世界が互いに干渉しないことになっているように見えます。変則的な monorepo と言いますか。

将来的には beta の中身がそっくりそのままリポジトリのルートを置き換え、現行のリポジトリルートにある（`beta` 以外の）内容はどこかにアーカイブされます。逆に、現在のリポジトリのルートにあるコードもスクリプトもあくまで現行のドキュメントサイトを担当しており、betaディレクトリの中身について一切関知してはいけません。

このPRでは、現行サイトを構築するためのスクリプトが beta に干渉してしまっていますし、将来 beta が本サイトに昇格する際にも問題が生じてしまいます。面倒でも、beta という別環境に、現行の textlint と同様のセットアップを再現する必要があると思います。`textlint/jp-reactjs-org-lint.js` もそのまま beta 内にコピーする感じですね。

2021-12-02 05:05 UTC, smikitky commented
言い方を変えると、クローンした後に beta ディレクトリだけ全く別の場所に動かしたとしても、現行サイトは beta なしで完璧にビルドできる必要がありますし、beta は beta で親フォルダにあったファイルへの依存なしに完璧にビルドできる必要があります。

2021-12-03 14:54 UTC, noyanyan commented
レビューありがとうございます！たしかにこのPRのままでは移行時に困りますね。

Betaディレクトリで独立して運用できるように、betaのpackage.jsonにtextlintとrule-presetを追加し、設定ファイルをコピーしようと思います。

2021-12-04 04:16 UTC, smikitky requested changes
普段は、lint-staged という NPM パッケージを利用して、コミット前のフックでコミット直前に当該ファイルのみに textlint を走らせています。それについては #126 をご覧ください。

#126 相当のものもここで含めてからマージできれば理想なのですが、いかがでしょうか。大変そうならそちらは別PRでやるのでも大丈夫です。

beta 側では既に husky が使われていますので、そちらの別途インストールは不要です。lint-staged を使って、既存の husky のセットアップを調整する形になります。

あと本家側でもコミット前に全部 prettier や eslint をかけるのではなく lint-staged を使ったらどうなの、と私がもちかけており(reactjs/reactjs.org#4143)、タイミングによりそちらとの干渉がありえることにも留意ください。

2021-12-04 04:16 UTC, smikitky commented on beta/package.json
> +    "lint:text": "textlint --rulesdir=./textlint  \"src/pages/**/*.md\" --cache",
これを実行してみると、2017年以前の、翻訳予定のないブログ記事に対しても大量に textlint がエラーを吐いています。親リポジトリ側の package.json にあるようなパターンを利用して本当に翻訳対象であるものだけをチェックするようにお願いします。

また、申し訳ないのですが、キャッシュも個人的には必要ないと思います。実際の日々の作業は lint-staged を使って本当にコミットする予定のものだけをチェックすることになっており、それはキャッシュがなくても高速です。この `lint:text` による全体チェックは、CI で自動チェックする場合や、本当に手でゼロから全体をチェックしなおしたい場合にのみ走らせるものですので、個人的には数秒のロスよりもキャッシュが悪さをすることによるエラーの方が怖いです。

2021-12-04 04:23 UTC, smikitky commented on beta/package.json
> +    "lint:text": "textlint --rulesdir=./textlint  \"src/pages/**/*.md\" --cache",
あと `src/pages/learn/javascript-in-jsx-with-curly-braces.md` も1カ所エラーを吐いているのですがそちらは[upstream で修正済み](https://github.com/reactjs/reactjs.org/pull/4138)なので放置で大丈夫です。

2021-12-04 04:30 UTC, noyanyan commented on package.json
> +    "lint:text": "textlint --rulesdir=./textlint  \"content/{docs,home,tutorial,warnings}/*.md\" \"content/blog/20[2-9]*.md\" --cache",
ごめんなさい、戻し忘れていました。(revert自体の意図としては、conteent/home/examples/a-simple-component.mdでlintエラーが出ており、beta関連のPRでこれを修正するべきでないという考えです。)
PR前の状態に差し戻します。

2021-12-04 04:37 UTC, noyanyan commented on beta/package.json
> +    "lint:text": "textlint --rulesdir=./textlint  \"src/pages/**/*.md\" --cache",
了解です。こちらも修正します。

2021-12-04 23:42 UTC, smikitky requested changes
1カ所だけ細かいですが修正お願いします。

（ちょっと自分の環境固有っぽい問題で動作確認がとれていないのでapproveは少しだけお待ちください）

2021-12-04 23:42 UTC, smikitky commented on package.json
> +    "lint:text": "textlint --rulesdir=./textlint  content/{docs,home,tutorial,warnings}/*.md content/blog/20[2-9]*.md",
一応余計なスペースの削除をお願いします

2021-12-04 23:43 UTC, smikitky commented on package.json
> +    "lint:text": "textlint --rulesdir=./textlint  content/{docs,home,tutorial,warnings}/*.md content/blog/20[2-9]*.md",
```suggestion
    "lint:text": "textlint --rulesdir=./textlint content/{docs,home,tutorial,warnings}/*.md content/blog/20[2-9]*.md",
```

2021-12-17 07:23 UTC, smikitky commented
うちの環境でこの PR をチェックアウトし、`cd beta; yarn` し、試しに何か commit しようとすると、`fatal: not a git repository: '.git'` というエラーが出てコミットできないのですが、同様のエラーは出ていますか？　クリーンインストールしてもダメでした。

以下の Issue をヒントに調べたところ、どうも `GIT_DIR` という環境変数が何らかの原因で `".git"` という文字列に設定されているのが原因です。git-cli が beta/.git という存在しないディレクトリのみを見に行っており、「親ディレクトリを順にたどって .git フォルダを探しに行く」という git-cli の通常動作が阻害されています。無理やり pre-commit ファイル内で `unset GIT_DIR` で環境変数消してみたらとりあえず動作はしました。

https://github.com/typicode/husky/issues/584

もうちょっと調べてみます…

2021-12-17 07:55 UTC, smikitky commented
https://stackoverflow.com/a/56026616/1209240

どうも pre-commit フック内で cd しようとすると面倒なよう。

どうせ本家側で lint-staged いれた時にまた考え直すことになるので、とりあえず日本版でうまく動くこと優先でいいかなと思います

2021-12-17 10:26 UTC, noyanyan commented
> うちの環境でこの PR をチェックアウトし、cd beta; yarn し、試しに何か commit しようとすると、fatal: not a git repository: '.git' というエラーが出てコミットできないのですが、同様のエラーは出ていますか？

自分の環境ではcommitできてます。なぜでしょうね。
WSL2 on Windows 11, Ubuntu Ubuntu 20.04.3 LTS.

とりあえず動くようにすることで良いと思いますが、この修正を@smikitkyさんにお願いできますか？
エラーが再現できる方が担当していただけたら安全だと思います。

2021-12-22 00:29 UTC, smikitky commented
@no-yan すみません、平日はなかなか時間がとれていないのですが "Allow edits from maintainers" というのはチェックされていますでしょうか。一度 push を試そうとしたら no write access と言われたので。

https://docs.github.com/ja/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

また、そちらの環境での `git version` の結果はどうでしょうか。どうも GIT_DIR をセットしているのは git 自身らしいので、もしかしたら自分の git version が古いのかも、というあたりを原因として疑っています。時間がかかってしまいすみません。

2021-12-22 04:39 UTC, no-yan commented
ありがとうございます。あまり急ぐ理由もないでしょうし、のんびりやっていきましょう。React 18リリースのタイミングでbetaに移行はないでしょうから。

以下の二点ですが、おそらく問題ないと思います。
- git version 2.33.1(最新版が2.34.1)
-  "Allow edits from maintainers"チェックあり
<img  src="https://user-images.githubusercontent.com/63000297/147035553-000764ae-1434-47e5-843c-531314d09674.png"/>

メインブランチからPRしており、これが疑わしい場合にはブランチを変更しますので言ってください。

2022-01-19 04:30 UTC, smikitky commented
懸念だった https://github.com/reactjs/reactjs.org/pull/4139 これがマージされ、これで目に見える問題は一通り解決しそうなので、これをマージするときに改めて見直したいと思います。遅くなり申し訳ありません。

2022-08-11 15:42 UTC, no-yan commented
一からPRを作ったほうが早いと思われる場合は、どなたでも躊躇なくPRを出していただいて構いません。
問題のエラーを自分の環境で再現できないため修正に取り組んでいませんが、ブロッカーになるならクローズされるほうが望ましいと思っています。

2022-08-15 04:14 UTC, smikitky commented
@no-yan お気遣いありがとうございます。そろそろ翻訳進めていかないとなーと思って手を付けられていないというだけです。仰る通り、これをベースにするより現状の最新からやりなおした方が早いとなったらそうさせていただくかもしれませんが、その場合はよろしくお願いします。

2023-05-16 01:50 UTC, smikitky commented
ごめんなさい、リポジトリ構成がとんでもなく変わったので、textlint のセットアップも全体的にゼロからやりなおすことにしました。こちらは close させていただきます。

新しい PR は #580 です。

2023-05-16 01:50 UTC, closed without merging