[WIP]Reacting to input with state翻訳
reactjs/ja.react.dev pull request #571
Opened 2023-05-10 14:24 UTC by youliangdao

2023-05-10 15:54 UTC, smikitky requested changes
ありがとうございます。夜遅いので今すぐ細かくは見られないのですが[訳語の統一](https://github.com/reactjs/ja.react.dev/wiki/%E8%A8%B3%E8%AA%9E%E3%81%AE%E7%B5%B1%E4%B8%80)と翻訳ガイドに従い、以下の点について対応をお願いします。

- 3 音以上の語の語尾の長音符は原則省略してください。「デザイナ」「ユーザ」「イベントハンドラ」など。
- 原則、declarative は「宣言的」ではなく「宣言**型**」、imperativeも「命令型」とするルールですので、「宣言型プログラミング」のようにしてください。ただし「UI を宣言的に考える」みたいなものまで無理に「-型」を使う必要はありません。
- "state" が useState で返ってくるコンポーネントメモリとしての state を指している場合は「状態」ではなく state と訳してください。state variable も「状態変数」ではなく「state 変数」としてください。「視覚状態」みたいなものは「状態」で構いません。
- 和文内の強調の前後にスペースを入れないでください。`あ *い* う` ではなく `あ*い*う` です。逆に和文の句読点の直後にスペースを入れないでください。`あ、 a` ではなく `あ、a` です。
- コード内で "Submit" と表示されているものを "送信" などに訳さないようにしてください。

2023-05-11 04:43 UTC, youliangdao commented
@smikitky さん、ご指摘ありがとうございます。
「訳語の統一」と翻訳ガイドに従い、基本的な訳語に関して訂正いたしました。

ご確認のほどよろしくお願いいたします。

2023-05-11 04:52 UTC, smikitky commented
[これ](https://docs.github.com/ja/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)を有効にしていただいているのですが、こちらでいくつか修正させていただいてマージするのと、ひとつひとつレビュー機能で指摘させていただくのとどちらがよいでしょうか？

スペースなど細かい体裁の問題がほとんどですが、いくつかは翻訳自体にも修正をお願いすることになりそうです。

2023-05-11 06:01 UTC, youliangdao commented
ご返信ありがとうございます。

レビュー機能でご指摘の方お願いいたします。

2023-05-13 02:22 UTC, smikitky requested changes
すみません、ひとつひとつ確認していたら指摘項目が大量になってしまいました。

AI 翻訳は作業の土台としてはよいですが文章がそのまま使えることはあまりないので、「人間だったらここでこんな翻訳はしない」みたいなところはかなり手を入れています。

あと数十回コミットするのではなく ["Add suggestion to batch" を使って](https://qiita.com/YusukeHosonuma/items/99cb430c7723bf991cfa)ください。

よろしくお願いします。

2023-05-13 02:22 UTC, smikitky commented on src/content/learn/reacting-to-input-with-state.md
> +* **ネットワーク応答の失敗**（コンピュータ）は、対応するエラーメッセージと共に*エラー*状態に切り替える必要があります。
```suggestion
* **テキスト入力フィールドの編集**（人間）により、テキストボックスが空かどうかによって、*Empty* 状態と *Typing* 状態を切り替える。
* **送信ボタンのクリック**（人間）により、*Submitting* 状態に切り替える。
* **ネットワーク応答の成功**（コンピュータ）により、*Success* 状態に切り替える。
* **ネットワーク応答の失敗**（コンピュータ）により、対応するエラーメッセージと共に *Error* 状態に切り替える。
```

2023-05-13 02:22 UTC, smikitky commented on src/content/learn/reacting-to-input-with-state.md
> +こちらは前回のチャレンジで、React を使わずに命令的に記述されたオリジナルのサンドボックスです。
```suggestion
こちらはひとつ前のチャレンジで、React を使わずに命令的に記述されたオリジナルのサンドボックスです。
```

2023-05-13 07:18 UTC, youliangdao commented
すべて確認して、"Add suggestion to batch"を適用いたしました。
またレビュー内容も、非常に参考になりました。丁寧なレビューありがとうございました。

2023-05-13 07:19 UTC, youliangdao commented
すべて確認して、"Add suggestion to batch"を適用いたしました。
またレビュー内容も、非常に参考になりました。丁寧なレビューありがとうございました。

2023-05-13 10:23 UTC, smikitky commented
すみません、指摘項目のうち一部（11件）しか対応されていないようです。恐らく以下を展開するのを忘れていたのではないかと思います。unresolve しておきましたので再確認をお願いします。

<img width="383" alt="image" src="https://github.com/reactjs/ja.react.dev/assets/7779406/c484a87e-2a6f-4b5b-b1ad-2e2ccb1288be">

2023-05-14 05:09 UTC, youliangdao commented
申し訳ございません。先ほどすべて反映させました。
確認していただけますと幸いです。よろしくお願いします。

2023-05-14 10:57 UTC, smikitky approved these changes
OKです、ありがとうございました！

2023-05-15 04:32 UTC, smikitky commented
マージは 2 名のメンテナが approve してからになりますのでもう少しお待ちください。

2023-05-15 05:58 UTC, koba04 commented
> マージは 2 名のメンテナが approve してからになりますのでもう少しお待ちください。

古い PR から順番にレビューしてるので少々お待ちください 🙏 
現在は #568 をレビュー中です。

2023-05-16 13:11 UTC, koba04 commented
@youliangdao 
サイドメニューの翻訳もお願いできますか？
https://github.com/reactjs/ja.react.dev/blob/main/src/sidebarLearn.json

2023-05-16 16:47 UTC, smikitky commented
些細なスペースの問題の修正と、サイドバーの翻訳を行いました。直接 push しました。

2023-05-18 16:00 UTC, koba04 approved these changes
👍 ありがとうございます！

2023-05-18 16:01 UTC, merged