Translate useDebugValue hook reference
reactjs/ja.react.dev pull request #573
Opened 2023-05-12 15:17 UTC by seckie

初めてのコントリビューションになります。
Reference > useDebugValue を試しに翻訳してみました。
GPT-4 をベースにして、既存の翻訳や legacy ドキュメントの翻訳の方針に沿っていない部分などを修正しています。

お役に立てそうであればDraftを解除します。ご確認よろしくお願いいたします。

2023-05-13 02:43 UTC, smikitky requested changes
ありがとうございます。

些細な訳語統一やフォーマットの指摘が殆どですが対応をお願いします。

React Dev Tools の inspect は訳すなら「検証」よりは「調査」が良いと思います。そういえば Chrome の開発者ツールもずっと「検証」を使っている気がしますが、個人的にはあれはいつも意味不明だなと思っています…。とはいえ今回は原文併記でカタカナにしておくのが無難な気がしました。

2023-05-13 02:43 UTC, smikitky commented on src/content/reference/react/useDebugValue.md
> +[以下にさらに例を示します。](#usage)
```suggestion
[さらに例を見る](#usage)
```

2023-05-13 02:43 UTC, smikitky commented on src/content/reference/react/useDebugValue.md
> +#### パラメータ {/*parameters*/}
```suggestion
#### 引数 {/*parameters*/}
```

2023-05-13 02:43 UTC, smikitky commented on src/content/reference/react/useDebugValue.md
> +これにより、`useOnlineStatus` を呼び出すコンポーネントを検証すると `OnlineStatus: "Online"` のようなラベルが付きます。
```suggestion
これにより、`useOnlineStatus` を呼び出すコンポーネントをインスペクト (inspect, 調査) すると `OnlineStatus: "Online"` のようなラベルが付きます。
```

2023-05-13 02:43 UTC, smikitky commented on src/content/reference/react/useDebugValue.md
> +`useDebugValue` の呼び出しがない場合、基本となるデータ（この例では `true`）のみが表示されます。
```suggestion
`useDebugValue` の呼び出しがない場合、元のデータ（この例では `true`）のみが表示されます。
```

2023-05-13 02:43 UTC, smikitky commented on src/content/reference/react/useDebugValue.md
> +すべてのカスタムフックにデバッグ値を追加しないでください。デバッグ値が最も有用なのは、共有ライブラリの一部であり、内部のデータ構造が複雑で検証が難しいカスタムフックです。
```suggestion
すべてのカスタムフックにデバッグ値を追加しないでください。デバッグ値が最も有用なのは、共有ライブラリの一部であり、内部のデータ構造が複雑で調査が難しいカスタムフックです。
```

2023-05-13 02:43 UTC, smikitky commented on src/content/reference/react/useDebugValue.md
> +`useDebugValue` の第 2 引数としてフォーマッタ関数も渡すことができます:
```suggestion
`useDebugValue` の第 2 引数としてフォーマッタ関数も渡すことができます：
```

2023-05-13 02:43 UTC, smikitky commented on src/content/reference/react/useDebugValue.md
> +あなたのフォーマッタ関数は、<CodeStep step={1}>デバッグ値</CodeStep>をパラメータとして受け取り、<CodeStep step={2}>フォーマットされた表示値</CodeStep>を返す必要があります。コンポーネントが検証されると、React DevTools はこの関数を呼び出し、その結果を表示します。
```suggestion
あなたのフォーマッタ関数は、<CodeStep step={1}>デバッグ値</CodeStep>をパラメータとして受け取り、<CodeStep step={2}>フォーマットされた表示値</CodeStep>を返す必要があります。コンポーネントがインスペクトされると、React DevTools はこの関数を呼び出し、その結果を表示します。
```

2023-05-13 02:43 UTC, smikitky commented on src/content/reference/react/useDebugValue.md
> +これにより、コンポーネントが実際に検証されない限り、コストがかかる可能性があるフォーマットロジックを実行することは回避できます。例えば、`date` が Date 値の場合、レンダーの度に `toDateString()` を呼び出すことを回避できます。
```suggestion
これにより、コンポーネントが実際にインスペクトされない限り、コストがかかる可能性があるフォーマットロジックを実行することを回避できます。例えば、`date` が Date 値の場合、レンダーの度に `toDateString()` を呼び出すことを回避できます。
```

2023-05-13 08:18 UTC, seckie commented on src/content/reference/react/useDebugValue.md
> +これにより、`useOnlineStatus` を呼び出すコンポーネントを検証すると `OnlineStatus: "Online"` のようなラベルが付きます。
@smikitky 早速のご確認ありがとうございます。
`Inspect` が最初に出てくるのが40行目の `format` 引数の文章なのですが、そちらの `検証` を `インスペクト (inspect, 調査)` とし、この行の `検証` は単に `インスペクト` とするのがよろしいでしょうか？

2023-05-13 09:59 UTC, smikitky commented on src/content/reference/react/useDebugValue.md
> +これにより、`useOnlineStatus` を呼び出すコンポーネントを検証すると `OnlineStatus: "Online"` のようなラベルが付きます。
見逃していました、それでお願いします。

2023-05-13 10:26 UTC, seckie commented on src/content/reference/react/useDebugValue.md
> +これにより、`useOnlineStatus` を呼び出すコンポーネントを検証すると `OnlineStatus: "Online"` のようなラベルが付きます。
@smikitky https://github.com/reactjs/ja.react.dev/pull/573/commits/83abe0a9e21cd50d3a99a82dce354b754bed54ac こちらで対応いたしました。

2023-05-13 10:28 UTC, smikitky approved these changes
ありがとうございました！
メンテナが 2 人 approve してからマージするルールになっていますのでもう少しお待ちください。

2023-05-21 13:59 UTC, koba04 approved these changes
👍 初コントリビューションありがとうございます！！！

2023-05-21 14:00 UTC, merged