Translate "useState"
reactjs/ja.react.dev pull request #595
Opened 2023-05-25 23:29 UTC by yuta-ike

リファレンスのuseStateのページの翻訳です

2023-05-26 00:28 UTC, yuta-ike commented on src/content/reference/react/useState.md
> +  * `nextState` に関数を渡した場合、その関数は*更新関数*として扱われます。更新関数は、純粋で、未確定の state (pending state) を唯一の引数として受け取り、次の state を返す必要があります。React は更新関数をキューに入れ、コンポーネントを再レンダーします。次のレンダーで、React はキューに入れられたすべての更新関数を前の state に対して
原文では、`pending state`と表現されている部分ですが、上手い訳語が見つからず「未確定の state (pending state)」としています。
良い語があれば教えていただけると嬉しいです。

2023-05-26 00:34 UTC, yuta-ike commented on src/content/reference/react/useState.md
> +state にオブジェクトや配列をセットすることができます。ただし React では、state は読み取り専用 (read-only) として扱う必要があります。そのため、state を更新する場合は、**既存のオブジェクトを直接*変更する (mutate)* のではなく、*置き換える (replace)* 必要があります**。例えば、state として `form` オブジェクトを保持してい
`mutate`を変更と訳してしまうと、"変更"が一般語で`change`との違いが汲み取れなくなってしまうので、「書き換え」に統一しました（replace=置き換え、mutate=書き換え、という釣り合いをとりたかったのもあります）。初出のこの文のみ、`(mutate)`のカッコを入れました。

他のページでは、「書き換え」と「ミューテーション」のどちらも利用されており、迷った部分です。何か指針などありますでしょうか？

2023-05-30 10:41 UTC, smikitky commented on src/content/reference/react/useState.md
> +state にオブジェクトや配列をセットすることができます。ただし React では、state は読み取り専用 (read-only) として扱う必要があります。そのため、state を更新する場合は、**既存のオブジェクトを直接*変更する (mutate)* のではなく、*置き換える (replace)* 必要があります**。例えば、state として `form` オブジェクトを保持してい
仰る通りの方針で大丈夫です。
「書き換え」と「ミューテーション」については、意図的に少々混在させながら（しかし誤解を招かないように気も使いながら）使っています。単に後者は長すぎて毎回使うのはどうかなという理由もありますし、まあ敢えて混ぜて使うことで概念に慣れてもらうのも有用かな、というくらいの感触です。（ほかには "route" も、「ルート」になったり「ページ」になったりしています）

2023-05-30 10:46 UTC, smikitky reviewed
ありがとうございます。
ぱっと見とてもよさそうなのですが、細かいレビューは後日とさせてください。

ひとまず、updater function は「更新用関数」に訳語統一をお願いします（[このページ](https://ja.react.dev/learn/queueing-a-series-of-state-updates)が初出のはずです）。（「用」を付けた深い意味は特にないです）

2023-05-31 02:38 UTC, smikitky requested changes
確認をお願いします。ほとんどは細かいスペースの問題などです。
「更新関数」については毎回指摘していないのでエディタで一括置換などをお願いします。

可能なら先に main をマージしていただいて `yarn textlint` を実行して、出てきた問題の対処をお願いします。

```
git merge reactjs/main
yarn textlint
```

2023-05-31 02:38 UTC, smikitky commented on src/content/reference/react/useState.md
> +これらがどれも適用できない稀なケースで、コンポーネントのレンダー中に `set` 関数を呼び出し、それまでにレンダーされた値に基づいて state を更新するパターンが利用できます。
```suggestion
これらがどれも適用できない稀なケースでは、コンポーネントのレンダー中に `set` 関数を呼び出し、それまでにレンダーされた値に基づいて state を更新するパターンが利用できます。
```

2023-05-31 02:39 UTC, smikitky commented on src/content/reference/react/useState.md
> +  * `nextState` に関数を渡した場合、その関数は*更新関数*として扱われます。更新関数は、純粋で、未確定の state (pending state) を唯一の引数として受け取り、次の state を返す必要があります。React は更新関数をキューに入れ、コンポーネントを再レンダーします。次のレンダーで、React はキューに入れられたすべての更新関数を前の state に対して
「処理中の state（の値）」などでも良さそうな気がしました。

2023-05-31 06:05 UTC, yuta-ike commented on src/content/reference/react/useState.md
> +  * `nextState` に関数を渡した場合、その関数は*更新関数*として扱われます。更新関数は、純粋で、未確定の state (pending state) を唯一の引数として受け取り、次の state を返す必要があります。React は更新関数をキューに入れ、コンポーネントを再レンダーします。次のレンダーで、React はキューに入れられたすべての更新関数を前の state に対して
ありがとうございます。「処理中の state の値」としました

2023-05-31 06:30 UTC, yuta-ike commented
ご確認ありがとうございます！修正しました。

2023-05-31 09:43 UTC, smikitky requested changes
すみません、幾つか見逃しがあったので微修正をお願いします 🙏🏻

2023-05-31 09:43 UTC, smikitky commented on src/content/reference/react/useState.md
> +#### フォーム (2 つの変数) {/*form-two-variables*/}
```suggestion
#### フォーム（2 つの変数） {/*form-two-variables*/}
```

2023-05-31 09:43 UTC, smikitky commented on src/content/reference/react/useState.md
> +詳しくは、[オブジェクトの state を更新する](/learn/updating-objects-in-state)や、[配列の state を更新する](/learn/updating-arrays-in-state)を参照してください。
```suggestion
詳しくは、[state 内のオブジェクトの更新](/learn/updating-objects-in-state)や、[state 内の配列の更新](/learn/updating-arrays-in-state)を参照してください。
```

2023-05-31 09:43 UTC, smikitky commented on src/content/reference/react/useState.md
> +state にオブジェクトや配列をセットすることができます。ただし React では、state は読み取り専用 (read-only) として扱う必要があります。そのため、state を更新する場合は、**既存のオブジェクトを直接*書き換える (mutate)* のではなく、*置き換える (replace)* 必要があります**。例えば、state として `form` オブジェクトを保持して
```suggestion
state にオブジェクトや配列をセットすることができます。ただし React では、state は読み取り専用として扱う必要があります。そのため、state を更新する場合は、**既存のオブジェクトを直接*書き換える (mutate)* のではなく、*置き換える (replace)* 必要があります**。例えば、state として `form` オブジェクトを保持している場合、以下のように書き換えを行ってはいけません。
```

ほかでも訳出していないので

2023-05-31 09:43 UTC, smikitky commented on src/content/reference/react/useState.md
> +  * `nextState` に関数を渡した場合、その関数は*更新用関数*として扱われます。更新用関数は、純粋で、処理中の state の値を唯一の引数として受け取り、次の state を返す必要があります。React は更新用関数をキューに入れ、コンポーネントを再レンダーします。次のレンダーで、React はキューに入れられたすべての更新用関数を前の state に対して適用し、次の sta
```suggestion
  * `nextState` に関数を渡した場合、その関数は*更新用関数 (updater function)* として扱われます。更新用関数は、純粋で、処理中の state の値を唯一の引数として受け取り、次の state を返す必要があります。React は更新用関数をキューに入れ、コンポーネントを再レンダーします。次のレンダーで、React はキューに入れられたすべての更新用関数を前の state に対して適用し、次の state を導出します。[例を見る](#updating-state-based-on-the-previous-state)
```

2023-05-31 09:43 UTC, smikitky commented on src/content/reference/react/useState.md
> +  * `initialState` に関数を渡した場合、その関数は*初期化関数*として扱われます。初期化関数は、純粋で、引数を取らず、何らかの型の値を返す必要があります。React はコンポーネントを初期化するときに初期化関数を呼び出し、その返り値を初期 state として保存します。[例を見る](#avoiding-recreating-the-initial-state)
```suggestion
  * `initialState` に関数を渡した場合、その関数は*初期化関数 (initializer function)* として扱われます。初期化関数は、純粋で、引数を取らず、何らかの型の値を返す必要があります。React はコンポーネントを初期化するときに初期化関数を呼び出し、その返り値を初期 state として保存します。[例を見る](#avoiding-recreating-the-initial-state)
```

2023-05-31 09:43 UTC, smikitky commented on src/content/reference/react/useState.md
> +ほとんどのケースでは、どちらのアプローチでも違いはありません。React は、クリックなどのユーザの意図的なアクションに対して、`age` state 変数の更新が次のクリックの前に発生することを保証しています。すなわち、イベントハンドラの開始時に、クリックハンドラが "古い (stale)" `age` を参照してしまうことはありません。
```suggestion
ほとんどのケースでは、どちらのアプローチでも違いはありません。React は、クリックなどのユーザの意図的なアクションに対して、`age` state 変数の更新が次のクリックの前に発生することを保証しています。すなわち、イベントハンドラの開始時に、クリックハンドラが「古い」`age` を参照してしまうことはありません。
```

何かの用語というわけでもないので訳さなくてもいいかなと

2023-05-31 12:32 UTC, yuta-ike commented
ありがとうございます。修正いたしました。

ちなみにですが、text-lint は見出しには適用されないのでしょうか？見出し中の半角カッコと全角カッコなどが、text-lintに引っかからず...

2023-05-31 13:53 UTC, smikitky approved these changes

2023-05-31 13:54 UTC, smikitky commented
ありがとうございました！

textlint は後で確認しておきます。blockquote 内をチェックするかの設定はどこかで見た気がしますが、見出しについては記憶にないです…

2023-06-20 13:47 UTC, koba04 approved these changes
👍 ありがとうございます！！！

2023-06-20 13:47 UTC, merged