Translate "Lifecycle of Reactive Effects"
reactjs/ja.react.dev pull request #601
Opened 2023-06-06 15:31 UTC by yuta-ike

"Lifecycle of Reactive Effects" の翻訳です

2023-06-08 06:33 UTC, smikitky requested changes
ありがとうとざいます。確認をお願いします！

2023-06-08 06:33 UTC, smikitky commented on src/content/learn/lifecycle-of-reactive-effects.md
> +このソリューションは問題なく機能しますが、理想的ではありません。エフェクト内に `console.log('Resubscribing')` を入れてみると、再レンダーのたびに再購読が発生していることがわかります。再購読は高速に動作するものの、それほど頻繁に行う必要はありません。
```suggestion
このソリューションは問題なく機能しますが、理想的ではありません。エフェクト内に `console.log('Resubscribing')` を入れてみると、再レンダーのたびにリスナの再登録が発生していることがわかります。再登録は高速に動作するものの、それほど頻繁に行わないようにした方が望ましいでしょう。
```

2023-06-08 06:33 UTC, smikitky commented on src/content/learn/lifecycle-of-reactive-effects.md
> +エフェクト本体に `console.log('Resubscribing')` を追加してみてください。チェックボックスを切り替えたとき（つまり `canMove` が変更されたとき）またはコードを編集したときに、再購読が発生することが分かります。これは、毎レンダーごとに再購読をしていた前のアプローチよりも優れています。
```suggestion
エフェクト本体に `console.log('Resubscribing')` を追加してみてください。チェックボックスを切り替えたとき（つまり `canMove` が変更されたとき）またはコードを編集したときに、リスナの再登録が発生することが分かります。これは、毎レンダーごとに再登録をしていた前のアプローチよりも優れています。
```

2023-06-08 06:33 UTC, smikitky commented on src/content/learn/lifecycle-of-reactive-effects.md
> +#### 接続の切り替えを修正する {/*fix-a-connection-switch*/}
```suggestion
#### 接続の切り替えを修正 {/*fix-a-connection-switch*/}
```

2023-06-08 06:33 UTC, smikitky commented on src/content/learn/lifecycle-of-reactive-effects.md
> +#### 一連の選択ボックスを埋める {/*populate-a-chain-of-select-boxes*/}
```suggestion
#### 連動する選択ボックスの作成 {/*populate-a-chain-of-select-boxes*/}
```

2023-06-08 06:33 UTC, smikitky commented on src/content/learn/lifecycle-of-reactive-effects.md
> +1 つ目の選択ボックスがどのように動作するか見てみましょう。`planetList` state 変数には、`"/planets"` API の呼び出し結果が格納されています。現在選択されている惑星の ID は `planetId` state 変数で保持されています。`placeList` state 変数に、`"/planets/" + planetId + "/places"` API の
```suggestion
1 つ目の選択ボックスがどのように動作するか見てみましょう。これは `"/planets"` API の呼び出し結果を格納している `planetList` state 変数から作られています。現在選択されている惑星の ID は `planetId` state 変数で保持されています。`placeList` という state 変数に、`"/planets/" + planetId + "/places"` API の呼び出し結果を格納するには、どこにコードを追加すればよいでしょうか。
```

2023-06-08 06:33 UTC, smikitky commented on src/content/learn/lifecycle-of-reactive-effects.md
> +このコードは少し冗長です。しかし、1 つのエフェクトにまとめるのは良い方法ではありません！ もしまとめてしまうと、両方のエフェクトの依存配列を 1 つにまとめる必要があります。そうすると、惑星を変更しただけで、惑星リストが再取得されてしまいます。エフェクトはコードを再利用するためのツールではありません。
```suggestion
このコードは少し冗長です。しかし、だからといって 1 つのエフェクトにまとめるのは良い方法ではありません！ もしまとめてしまうと、両方のエフェクトの依存配列を 1 つにまとめる必要があります。そうすると、惑星を変更しただけで、惑星リストが再取得されてしまいます。エフェクトはコードを再利用するためのツールではありません。
```

2023-06-09 03:43 UTC, yuta-ike commented on src/content/learn/lifecycle-of-reactive-effects.md
> +先ほどはコンポーネントの視点で考えていました。コンポーネントの視点から見ると、エフェクトは、"レンダー直後" や "アンマウント直前" のように特定のタイミングで発生する "コールバック関数" や "ライフサイクル中のイベント" と考えたくなります。しかし、このような考え方はすぐにややこしくなるため、避けた方が無難です。
知りませんでした...! ありがとうございます

2023-06-09 03:48 UTC, yuta-ike commented on src/content/learn/lifecycle-of-reactive-effects.md
> +[次](/learn/separating-events-from-effects)の[ページ](/learn/removing-effect-dependencies)では、ルールを破らずにこれらのコードを修正する方法を学びます。必ず修正する価値があります！
ああ、そういうことだったんですね。。不思議に思いながら直訳してしまいました。ありがとうございます

2023-06-09 03:54 UTC, yuta-ike commented on src/content/learn/lifecycle-of-reactive-effects.md
> +この例では、エフェクトが window の [`pointermove`](https://developer.mozilla.org/en-US/docs/Web/API/Element/pointermove_event) イベントを購読し、画面上のピンクのドットを移動させています。プレビューエリアにカーソルを合わせてみてください（モバイルデバイスの場合は画面をタッチしてください）。ピンクの
購入してないから、ということなんでしょうか。確かによく考えると変な感じもしてきますね。。

2023-06-09 04:48 UTC, smikitky approved these changes
ありがとうございます。分かりやすく訳して頂いて助かります。

2023-06-09 04:48 UTC, smikitky approved these changes
ありがとうございます。分かりやすく訳して頂いて助かります。

2023-06-23 14:36 UTC, koba04 approved these changes
👍 ありがとうございます！！！

2023-06-23 14:36 UTC, merged