Complete useID page
reactjs/ja.react.dev pull request #608
Opened 2023-06-13 19:08 UTC by sbasken

2023-06-14 09:33 UTC, smikitky requested changes
ありがとうございます。レビューについての確認をお願いします。ほとんどはスペースや他のページとの整合性を保つための細かい問題です。

2023-06-14 09:33 UTC, smikitky commented on src/content/reference/react/useId.md
> +複数の関連要素に ID を与える必要がある場合は、`useId` を呼び出してそれらの共有プレフィックスを生成できます。
```suggestion
複数の関連要素に ID を与える必要がある場合は、`useId` で生成した値を共有のプレフィックスとして使用できます。
```

すみません、読んだとき少し理解しづらく感じたので意訳しました

2023-06-14 16:19 UTC, sbasken commented
丁寧にご確認ありがとうございました！スタイルや表現法、覚えておきます😊　訂正して、新たにコミットしておきましたので確認よろしくお願いします。

2023-07-04 10:31 UTC, koba04 approved these changes
👍 ありがとうございます！！！

2023-07-04 10:31 UTC, merged