Translate "Separating Events from Effects"
reactjs/ja.react.dev pull request #609
Opened 2023-06-14 12:46 UTC by kotaesaki

"Separating Events from Effects"の翻訳です！

- [x] Choosing between event handlers and Effects 
- [x] Reactive values and reactive logic
- [x] Extracting non-reactive logic out of Effects
- [x] Recap
- [x] challenges

2023-06-20 12:06 UTC, kotaesaki commented
お待たせして申し訳ございません。レビューよろしくお願いします！

2023-07-04 10:34 UTC, koba04 commented
@smikitky こちらのレビューもお願いできると助かります 🙏

2023-07-05 17:22 UTC, smikitky commented
ちょっと勘違いしてこちらが後回しになっており申し訳ありません。
レビューはほぼ完了しているのですが見直しているところです。お待ち下さい。

2023-07-15 06:04 UTC, smikitky requested changes
大変遅くなり申し訳ありません。数が多いですがよろしくお願いします。

ちなみに interaction は、厳しく統一はしていませんが、他の記事では「インタラクション」よりもどちらかというと「ユーザ操作」「操作」を好む、という感じで訳しています。

2023-08-15 01:02 UTC, koba04 commented
@kotaesaki 
翻訳ありがとうございます！こちらのレビュー結果の反映は可能そうでしょうか？

2023-08-15 10:41 UTC, kotaesaki commented
@koba04 
こちらまだ手がつけられていない状況になっています。遅れていて大変申し訳ございません。

今週日曜までに修正させていただきます。よろしくお願いいたします。

2023-08-15 11:04 UTC, koba04 commented
@kotaesaki いえいえ、お時間ある時で大丈夫ですのでよろしくお願いします！🙇‍♂️

2023-08-20 09:28 UTC, kotaesaki commented
@smikitky @koba04 
大変遅れました🙇指摘箇所修正致しましたので再度レビューよろしくお願いいたします！

2023-08-20 11:47 UTC, smikitky approved these changes
ありがとうございました！

2023-08-21 14:58 UTC, koba04 approved these changes
👍 ありがとうございます！！！

2023-08-21 14:58 UTC, merged