Translate "useRef" reference
reactjs/ja.react.dev pull request #613
Opened 2023-06-25 01:32 UTC by yuta-ike

リファレンスの "useRef" の翻訳です

2023-06-25 01:49 UTC, yuta-ike commented on src/content/reference/react/useRef.md
> +これらのルールを破っていても、コンポーネントは正常に動作し続けるかもしれません。しかし、近いうちに React に追加される新機能の多くは、これらのルールが守られることを前提としています。詳しくは[コンポーネントを純粋に保つ](/learn/keeping-components-pure#where-you-can-cause-side-effects)を参照してください。
こちらのリンクのアンカーIDですが、正しくは `#where-you-_can_-cause-side-effects` なのですが、原文ではアンダースコアが抜けてしまっています。そのため、現在は該当のセクションへ遷移しない状態です。

本家にも [PR](https://github.com/reactjs/react.dev/pull/6115) を出してみたのですが、こちらのレポジトリはどうするのが良いでしょうか？

2023-06-26 03:39 UTC, smikitky commented on src/content/reference/react/useRef.md
> +これらのルールを破っていても、コンポーネントは正常に動作し続けるかもしれません。しかし、近いうちに React に追加される新機能の多くは、これらのルールが守られることを前提としています。詳しくは[コンポーネントを純粋に保つ](/learn/keeping-components-pure#where-you-can-cause-side-effects)を参照してください。
- 原文の些細な文法ミス（読者が混乱しないもの）は黙って修正
- 原文の説明自体の明らかなミス（読者が混乱しかねないもの）やこういうコードエラーは、原文に PR 出しつつ黙って修正

という感じでやっています。とりあえず日本語版で先に修正しておいて頂いて大丈夫です。

2023-06-27 08:00 UTC, yuta-ike commented on src/content/reference/react/useRef.md
> +これらのルールを破っていても、コンポーネントは正常に動作し続けるかもしれません。しかし、近いうちに React に追加される新機能の多くは、これらのルールが守られることを前提としています。詳しくは[コンポーネントを純粋に保つ](/learn/keeping-components-pure#where-you-can-cause-side-effects)を参照してください。
ありがとうございます。修正しました。（元PRもマージされていました）

2023-06-29 05:48 UTC, smikitky requested changes
ありがとうございます。
細かいものがほとんどですが対応をお願いします。

2023-06-29 05:48 UTC, smikitky commented on src/content/reference/react/useRef.md
> +この例では、ボタンがクリックされると、その画像が画面に表示されるようにスクロールします。ref を使用してリストの DOM ノードを取得し、DOM の [`querySelectorAll`](https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelectorAll) API を呼び出して、スクロールしたい画像を探してい
```suggestion
この例では、ボタンがクリックされると、その画像が画面に表示されるようにスクロールします。ref を使用してリストの DOM ノードを取得し、DOM の [`querySelectorAll`](https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelectorAll) API を呼び出して、スクロール先の画像を探しています。
```

2023-07-04 05:07 UTC, yuta-ike commented
レビューありがとうございます！修正 done です。

2023-07-04 06:48 UTC, smikitky approved these changes
ありがとうございます！

2023-07-07 13:51 UTC, koba04 approved these changes
👍 ありがとうございます！

2023-07-07 13:51 UTC, merged