Translate useImperativeHandle reference
reactjs/ja.react.dev pull request #614
Opened 2023-06-29 17:44 UTC by sbasken

2023-07-01 10:25 UTC, smikitky commented
レビューは順に行いますが、先に [rebase と push -f](https://rurukblog.com/post/git-rebase-commit/) でコミットをまとめていただけるようお願いします。

2023-07-06 04:04 UTC, smikitky commented
先にブランチをチェックアウトしていないのかもしれません。

- `git checkout useImperativeHandle` # ブランチをチェックアウト
- `git rebase main -i` # 現在のブランチを main から生えているかのように再構成せよ、その際にコミットを統合したり入れ替えたりするための対話モード (`-i`) に入れ
- `git push -f` # fast-forward でなくても push せよ

で、どうでしょう。

2023-07-06 14:57 UTC, sbasken commented
@smikitky 丁寧に教えてくださってありがとうございました！！なんとかできたと思うので、お手隙の際にご確認よろしくお願いします。

2023-07-15 06:46 UTC, smikitky requested changes
遅くなりましたがこちらの対応をよろしくお願いします。

2023-07-15 06:46 UTC, smikitky commented on src/content/reference/react/useImperativeHandle.md
> +* `ref`: [`forwardRef` render 関数](/reference/react/forwardRef#render-function)から 2 番目の引数として受け取った `ref` です。
```suggestion
* `ref`: [`forwardRef` レンダー関数](/reference/react/forwardRef#render-function)から 2 番目の引数として受け取った `ref` です。
```

2023-07-15 06:46 UTC, smikitky commented on src/content/reference/react/useImperativeHandle.md
> +## 使用方 {/*usage*/}
```suggestion
## 使用法 {/*usage*/}
```

2023-07-15 06:46 UTC, smikitky commented on src/content/reference/react/useImperativeHandle.md
> +デフォルトでは、コンポーネントはその DOM ノードを親コンポーネントに公開しません。例えば、`MyInput` の親コンポーネントが `<input>` DOM ノードに[アクセスできるように](/learn/manipulation-the-dom-with-refs)したい場合は、[`forwardRef`](/reference/react/forwardRef) にオプトインする必要が
```suggestion
デフォルトでは、コンポーネントはその DOM ノードを親コンポーネントに公開しません。例えば、`MyInput` の親コンポーネントが `<input>` DOM ノードに[アクセスできるように](/learn/manipulation-the-dom-with-refs)したい場合は、[`forwardRef`](/reference/react/forwardRef) を使って明示的に許可する必要があります。 
```

2023-07-15 06:46 UTC, smikitky commented on src/content/reference/react/useImperativeHandle.md
> +      // ... あなたのメソッド ...
```suggestion
      // ... your methods ...
```

よほど理解に支障のある長文などでない限りは訳さないルールにしています

2023-07-15 06:46 UTC, smikitky commented on src/content/reference/react/useImperativeHandle.md
> +例えば、`<input>` DOM ノード全体を公開するのではなく、その 2 つのメソッド、`focus` と `scrollIntoView` を公開したいとします。これを行うには、実際のブラウザの DOM を別の ref に保持します。そして、`useImperativeHandle` を使用して、親コンポーネントに呼び出したいメソッドのみを含むハンドルを公開します。
```suggestion
例えば、`<input>` DOM ノード全体を公開したくはないが、その 2 つのメソッド、`focus` と `scrollIntoView` は公開したいとします。これを行うには、実際のブラウザの DOM を別の ref に保持しておきます。そして、`useImperativeHandle` を使用して、親コンポーネントに呼び出してほしいメソッドのみを含むハンドルを公開します。
```

2023-07-15 06:46 UTC, smikitky commented on src/content/reference/react/useImperativeHandle.md
> +これで、親コンポーネントが `MyInput` への ref を取得し、そのコンポーネントで `focus` メソッドと `scrollIntoView` メソッドを呼び出すことができるようになります。ただし、親コンポーネントは基礎となる `<input>` DOM ノードへの完全なアクセス権は持ちません。
```suggestion
これで、親コンポーネントが `MyInput` への ref を取得し、そのコンポーネントで `focus` メソッドと `scrollIntoView` メソッドを呼び出すことができるようになります。ただし、親コンポーネントは背後にある `<input>` DOM ノードへの完全なアクセス権は持ちません。
```

2023-07-15 06:46 UTC, smikitky commented on src/content/reference/react/useImperativeHandle.md
> +    // DOM ノードが公開されていないため、これでは機能しません。
```suggestion
    // This won't work because the DOM node isn't exposed:
```

2023-07-15 06:46 UTC, smikitky commented on src/content/reference/react/useImperativeHandle.md
> +**ref の過度な使用に注意してください。**ref は、prop として表現できない、*命令形式*の動作にのみ使用するべきです。例えば、ノードへのスクロール、ノードへのフォーカス、アニメーションのトリガ、テキストの選択などです。
```suggestion
**ref の過度な使用に注意してください。**ref は、props として表現できない、*命令型*の動作にのみ使用するべきです。例えば、ノードへのスクロール、ノードへのフォーカス、アニメーションのトリガ、テキストの選択などです。
```

2023-07-15 06:46 UTC, smikitky commented on src/content/reference/react/useImperativeHandle.md
> +**何かを prop として表現できる場合は、ref を使用すべきではありません。**例えば、`Modal` コンポーネントから `{ open, close }` のような命令形式のハンドルを公開するのではなく、`<Modal isOpen={isOpen} />`のように、`isOpen` を prop として受け取る方が良いでしょう。[エフェクト](/learn/synchronizing
```suggestion
**何かを props として表現できる場合は、ref を使用すべきではありません。**例えば、`Modal` コンポーネントから `{ open, close }` のような命令型のハンドルを公開するのではなく、`<Modal isOpen={isOpen} />` のように、`isOpen` を props として受け取る方が良いでしょう。命令型の動作を props として公開する際には[エフェクト](/learn/synchronizing-with-effects)が役立ちます。
```

この文脈ではあくまでエフェクトは補助的な道具に過ぎないので最後の部分は "help" のニュアンスを加えました。

2023-07-15 06:46 UTC, smikitky commented on src/content/reference/react/useImperativeHandle.md
> +* **オプション** `dependencies`: `createHandle` のコード内でリファレンスされるすべてのリアクティブな値のリストです。リアクティブな値には、props、state、およびコンポーネント内で直接宣言された変数と関数が含まれます。もし linter が [React 向けに設定](/learn/editor-setup#linting)されている場合、linter
```suggestion
* **省略可能** `dependencies`: `createHandle` コード内で参照されるすべてのリアクティブな値のリストです。リアクティブな値には、props、state、コンポーネント本体に直接宣言されたすべての変数および関数が含まれます。リンタが [React 用に設定されている場合](/learn/editor-setup#linting)、すべてのリアクティブな値が依存値として正しく指定されているか確認できます。依存値のリストは要素数が一定である必要があり、`[dep1, dep2, dep3]` のようにインラインで記述する必要があります。React は、[`Object.is`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/is) を使った比較で、それぞれの依存値を以前の値と比較します。再レンダーにより依存値のいずれかが変更された場合、または引数自体を省略した場合、`createHandle` 関数は再実行され、新しく作成されたハンドルが ref に割り当てられます。
```

useEffect などすでに翻訳済みのほうと訳文を合わせました

2023-07-18 07:58 UTC, smikitky approved these changes
ありがとうございました！

小さな URL エラーやマークアップエラーがあったのでこちらで修正させていただきました。

2023-07-19 15:37 UTC, koba04 approved these changes
👍 ありがとうございます！

2023-07-19 15:37 UTC, merged