Translate "Hooks" index page
reactjs/ja.react.dev pull request #618
Opened 2023-07-10 03:29 UTC by Hayao0819

`src/content/reference/react/index.md`を翻訳しました。

Issue: https://github.com/reactjs/ja.react.dev/issues/452#issuecomment-1614172040

**各ページへのリンクについて**

各ページへのリンクの概要の文章は私が翻訳しましたが、各ページのリンク先の翻訳を引用したほうが良いでしょうか？

**Textlintについて**

https://github.com/reactjs/ja.react.dev/issues/616 での通り、`textlint`ディレクトリに入った状態でのみ`textlint`が正常に動作しました。Gitへのコミット時にはtextlintを無効化してコミットしていますが、textlintでエラーや警告が出ないことは確認済みです。

2023-07-15 06:12 UTC, smikitky requested changes
すみません、個別のレビューに入る前に以下の対応をお願いできないでしょうか。

- 原文と訳文で行番号を厳密に一致させる（2か所余計な改行や重複があります）
- state, ref などは文頭でも小文字にする。props などの常に複数形を使うと決めたものを除き、refs, keys などの複数形は訳文では使わない。
- 「コンテクスト」「エフェクト」などカタカナで訳すと決まっているものを英単語のままで残さない。

よろしくお願いします。

2023-07-18 02:35 UTC, Hayao0819 commented
単語の統一と行数の修正、その他誤字の修正を行いました。
再度確認をよろしくお願いいたします。

2023-07-18 07:48 UTC, smikitky requested changes
レビューを行いましたので確認をお願いします。

訳語統一関連の指摘が多くなっていますので、[訳語統一ページ](https://github.com/reactjs/ja.react.dev/wiki/%E8%A8%B3%E8%AA%9E%E3%81%AE%E7%B5%B1%E4%B8%80)を改めてご確認いただければ幸いです。

2023-07-18 07:48 UTC, smikitky commented on src/content/reference/react/index.md
> +これらのフックはライブラリの開発者には便利かもしれません。しかし、アプリケーションのコードでは通常は用いられることはありません。
```suggestion
これらのフックはライブラリの開発者には有用ですが、アプリケーションコードでは通常は用いられることはありません。
```

直訳で問題ないので1文にまとめました

2023-07-18 07:48 UTC, smikitky commented on src/content/reference/react/index.md
> +- [`useId`](/reference/react/useId) を用いると、コンポーネントがユニークな ID をコンポーネントそのものに関連付けることができます。通常はアクセシビリティ API とともに使用されます。
```suggestion
- [`useId`](/reference/react/useId) を用いると、コンポーネントにユニークな ID を関連付けることができます。通常はアクセシビリティ API とともに使用されます。 
```

2023-07-18 07:48 UTC, smikitky commented on src/content/reference/react/index.md
> +独自のカスタムフックを[ JavaScript の関数として定義](/learn/reusing-logic-with-custom-hooks#extracting-your-own-custom-hook-from-a-component)することもできます。
```suggestion
JavaScript の関数として[独自のカスタムフックを定義](/learn/reusing-logic-with-custom-hooks#extracting-your-own-custom-hook-from-a-component)することもできます。
```

2023-07-18 07:48 UTC, smikitky commented on src/content/reference/react/index.md
> +`useEfefct` には、タイミングの違いによってまれに使われることのある 2 つのバリエーションがあります：
```suggestion
`useEffect` には、実行タイミングが異なり、まれに使われることのある 2 つのバリエーションがあります： 
```

2023-07-18 07:48 UTC, smikitky commented on src/content/reference/react/index.md
> +再レンダーのパフォーマンスを最適化する通常の方法は、不要な処理を減らすことです。例えばキャッシュを再利用したり、データの変更がない場合の再レンダーをスキップしたりするよう、React に伝えることができます。
```suggestion
再レンダーのパフォーマンスを最適化するためのよくある方法は、不要な処理を減らすことです。例えばキャッシュ済みの計算結果を再利用したり、データの変更がない場合の再レンダーをスキップしたりするよう、React に伝えることができます。
```

キャッシュとは仕組みを指す言葉なので、キャッシュ自体を再利用することはできません

2023-07-19 02:40 UTC, Hayao0819 commented
翻訳の統一は十分注意したつもりだったんですが見落としがかなりあったようです。申し訳ありません。

2023-07-19 03:17 UTC, smikitky commented
訳語集に載っていないものもありますし、全文目を通しているのはメンテナくらいなので気にしないで大丈夫です！

https://github.com/reactjs/ja.react.dev/pull/618/files

問題なければ、上記のページから「Add suggestion to batch」機能を使ってまとめてコミットしていただけると助かります。

2023-07-19 03:44 UTC, Hayao0819 commented
レビューの変更と、その他自分で見つけた場所を修正しました。

2023-07-19 03:47 UTC, smikitky approved these changes
ありがとうございました！

2 名のレビュアーが approve してからマージされますので、このままお待ちください。

2023-07-20 10:40 UTC, koba04 approved these changes
👍 ありがとうございます！

2023-07-20 10:49 UTC, merged