Translate useExternalStore reference
reactjs/ja.react.dev pull request #619
Opened 2023-07-10 14:35 UTC by jp-knj

`useExternalStore` の翻訳です

2023-07-15 08:18 UTC, smikitky requested changes
レビューを行いましたので対応をお願いします。

ChatGPT を信用せず、全文丁寧に添削する方向でお願いします。訳抜けやタグ抜け、明らかな誤訳が結構放置されています。またローカルで dev server を立ち上げて、そもそもちゃんとページの表示ができているかの確認をお願いします。

2023-07-15 08:18 UTC, smikitky commented on src/content/reference/react/useSyncExternalStore.md
> +`getServerSnapshot` が最初のクライアントレンダリングで、サーバで返したのと同じ正確なデータを返すことを確認してください。例えば、`getServerSnapshot` がサーバ上で事前に準備されたストアコンテンツを返した場合、このコンテンツをクライアントに転送する必要があります。これを行う 1 つの方法は、サーバレンダリング中に `window.MY_STORE_DATA`
```suggestion
初回のクライアントレンダリングでは、`getServerSnapshot` はサーバで返したものと必ず正確に同一のデータを返すようにしてください。例えば、`getServerSnapshot` がサーバ上で事前に準備されたストアコンテンツを返した場合、このコンテンツをクライアントに転送する必要があります。これを行う 1 つの方法は、サーバレンダリング中に `window.MY_STORE_DATA` のようなグローバル変数を設定する `<script>` タグを発行しておき、クライアントの `getServerSnapshot` でそのグローバル変数から読み込むことです。あなたが使う外部ストアにその方法が記載されているはずです。
```

2023-07-15 08:18 UTC, smikitky commented on src/content/reference/react/useSyncExternalStore.md
> +## トラブルシューティング {/troubleshooting/} {/*トラブルシューティング-troubleshooting*/}
```suggestion
## トラブルシューティング {/*troubleshooting*/}
```

2023-07-15 08:18 UTC, smikitky commented on src/content/reference/react/useSyncExternalStore.md
> +### エラーが出ています: "getSnapshot の結果はキャッシュされるべきです" {/im-getting-an-error-the-result-of-getsnapshot-should-be-cached/} {/*エラーが出ています-getsnapshot-の結果はキャッシュされるべきです-im-getting-an-error-the-result-of-getsnapsho
```suggestion
### "The result of `getSnapshot` should be cached" というエラーが出る {/*im-getting-an-error-the-result-of-getsnapshot-should-be-cached*/}
```

2023-07-15 08:18 UTC, smikitky commented on src/content/reference/react/useSyncExternalStore.md
> +このエラーは、`getSnapshot` 関数が呼ばれるたびに新しいオブジェクトを返すことを意味します。例えば：
```suggestion
このエラーは、`getSnapshot` 関数が呼ばれるたびに新しいオブジェクトを返していることを意味します。例えば：
```

2023-07-15 08:18 UTC, smikitky commented on src/content/reference/react/useSyncExternalStore.md
> +  // 🔴 getSnapshot から常に異なるオブジェクトを返しません
```suggestion
  // 🔴 Do not return always different objects from getSnapshot
```

2023-07-15 08:18 UTC, smikitky commented on src/content/reference/react/useSyncExternalStore.md
> +`getSnapshot` の戻り値が前回と異なる場合、React はコンポーネントを再レンダーします。このため、常に異なる値を返すと無限ループに入り、次のようなエラーが発生します。
```suggestion
`getSnapshot` の返り値が前回と異なる場合、React はコンポーネントを再レンダーします。このため、常に異なる値を返すと無限ループに入り、このエラーが発生します。
```

2023-07-15 08:18 UTC, smikitky commented on src/content/reference/react/useSyncExternalStore.md
> +  // ✅ イミュータブルなデータを返すことができます
```suggestion
  // ✅ You can return immutable data
```

2023-07-15 08:18 UTC, smikitky commented on src/content/reference/react/useSyncExternalStore.md
> +ストアデータが変更可能な場合、`getSnapshot` 関数はその不変スナップショットを返す必要があります。つまり、新しいオブジェクトを作成する必要が**あります**が、毎回呼び出す必要はありません。その代わりに、最後に計算されたスナップショットを保存し、ストア内のデータが変更されていない場合は前回と同じスナップショットを返すようにします。ミュータブルなデータが変更されたかどうかをどのように判
```suggestion
ストアデータがミュータブルな場合、`getSnapshot` 関数はそのイミュータブルなスナップショットを返す必要があります。つまり、新しいオブジェクトを作成する必要は**あります**が、毎回作成してはいけないということです。その代わりに、最後に計算されたスナップショットを保存しておき、ストア内のデータが変更されていない場合は前回と同じスナップショットを返すようにします。ミュータブルなデータが変更されたかどうかを判断する方法は、ミュータブルなストアによって異なります。
```

2023-07-15 08:18 UTC, smikitky commented on src/content/reference/react/useSyncExternalStore.md
> +### `subscribe` 関数が毎回の再レンダー後に呼び出されます {/my-subscribe-function-gets-called-after-every-re-render/} {/*subscribe-関数が毎回の再レンダー後に呼び出されます-my-subscribe-function-gets-called-after-every-re-render*/}
```suggestion
### `subscribe` が毎レンダーごとに呼び出される {/*my-subscribe-function-gets-called-after-every-re-render*/}
```

2023-07-15 08:18 UTC, smikitky commented on src/content/reference/react/useSyncExternalStore.md
> +この `subscribe` 関数はコンポーネントの**内部**で定義されるため、再レンダーするたびに異なります：
```suggestion
この `subscribe` 関数はコンポーネントの**内部**で定義されているため、再レンダーするたびに異なった値になります：
```

2023-07-15 08:18 UTC, smikitky commented on src/content/reference/react/useSyncExternalStore.md
> +  // 🚩 常に異なる関数であるため、React は再レンダーのたびに再サブスクライブします
```suggestion
  // 🚩 Always a different function, so React will resubscribe on every re-render
```

2023-07-15 08:18 UTC, smikitky commented on src/content/reference/react/useSyncExternalStore.md
> +React は、再レンダーの間に別の `subscribe` 関数を渡すと、ストアに再サブスクライブします。これがパフォーマンスの問題を引き起こし、再サブスクライブを避けたい場合は、`subscribe` 関数を外部に移動してください：
```suggestion
React は、再レンダー間で異なる `subscribe` 関数を渡すと、ストアに再サブスクライブします。これがパフォーマンスの問題を引き起こし、再サブスクライブを避けたい場合は、`subscribe` 関数を外部に移動してください：
```

2023-07-15 08:18 UTC, smikitky commented on src/content/reference/react/useSyncExternalStore.md
> +// ✅ 常に同じ関数です、なので React は再サブスクライブする必要がありません
```suggestion
// ✅ Always the same function, so React won't need to resubscribe
```

2023-07-15 08:18 UTC, smikitky commented on src/content/reference/react/useSyncExternalStore.md
> +  // ✅ userId が変わらない限り同じ関数になります
```suggestion
  // ✅ Same function as long as userId doesn't change
```

2023-07-15 12:00 UTC, jp-knj commented on src/content/reference/react/useSyncExternalStore.md
> +// 代わりに React state を使用することをお勧めします。
8c6c2ef のコミットで対応しました。
確認お願いします。

2023-07-15 12:05 UTC, jp-knj commented
@smikitky 
レビューの修正対応しました。
-  dev server を立ち上げして、確認しました。
- code suggestion を commit を squash して push -f して反映しました。

お手数おかけしますが、再度レビューお願いします。

2023-07-15 12:43 UTC, smikitky requested changes
ありがとうございます。ほぼ OK なのですが幾つか私の方で見逃しがあったので対応をお願いします:pray:

2023-07-15 12:43 UTC, smikitky commented on src/content/reference/react/useSyncExternalStore.md
> +* `subscribe`: ストアにサブスクライブを開始し、また callback 引数を受け取る関数。ストアが変更された際に渡された callback を呼び出す必要があります。これにより、コンポーネントが再レンダーされます。subscribe 関数は、サブスクリプションをクリーンアップする関数を返す必要があります。
```suggestion
* `subscribe`: ストアにサブスクライブを開始し、また callback 引数を受け取る関数。ストアが変更された際に渡された callback を呼び出す必要があります。これにより、コンポーネントが再レンダーされます。`subscribe` 関数は、サブスクリプションをクリーンアップする関数を返す必要があります。
```

2023-07-15 12:43 UTC, smikitky commented on src/content/reference/react/useSyncExternalStore.md
> +* `getSnapshot`: コンポーネントが必要とするストアにあるデータのスナップショットを返す関数。ストアが変更されていない場合、getSnapshot への再呼び出しは同じ値を返す必要があります。ストアが変更されて返された値が（[`Object.is`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/
```suggestion
* `getSnapshot`: コンポーネントが必要とするストアにあるデータのスナップショットを返す関数。ストアが変更されていない場合、`getSnapshot` への再呼び出しは同じ値を返す必要があります。ストアが変更されて返された値が（[`Object.is`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/is) で比較して）異なる場合、React はコンポーネントを再レンダーします。
```

2023-07-15 12:43 UTC, smikitky commented on src/content/reference/react/useSyncExternalStore.md
> +`useSyncExternalStore` を追加するもう 1 つの理由は、時間とともに変化するブラウザが公開する値にサブスクライブしたい場合です。たとえば、コンポーネントがネットワーク接続がアクティブかどうかを表示したいとします。ブラウザは、この情報を [`navigator.onLine`](https://developer.mozilla.org/en-US/docs/Web/API/
```suggestion
`useSyncExternalStore` を追加するもう 1 つの理由は、時間とともに変化する、ブラウザが公開する値にサブスクライブしたい場合です。たとえば、コンポーネントがネットワーク接続がアクティブかどうかを表示したいとします。ブラウザは、この情報を [`navigator.onLine`](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/onLine) というプロパティを介して公開します。
```

2023-07-15 12:57 UTC, jp-knj commented
レビュー、ありがとうございます！

71ea816 で code suggestion を squash して push -f して反映しました。

よろしくお願いします🙏

2023-07-15 13:51 UTC, smikitky approved these changes

2023-07-15 13:51 UTC, smikitky commented
ありがとうございました！ 2 名が approve してからのマージになりますのでしばらくお待ちください。

2023-07-17 15:04 UTC, koba04 approved these changes
👍 ありがとうございます！！！

2023-07-17 15:04 UTC, merged