Translate useContext reference
reactjs/ja.react.dev pull request #621
Opened 2023-07-15 12:28 UTC by jp-knj

2023-07-16 07:52 UTC, jp-knj commented on src/content/reference/react/useContext.md
> +### フォールバックの初期値の指定 {/*specifying-a-fallback-default-value*/}
default value をデフォルト値か初期値に翻訳するか迷いましたが、[デフォルト値](https://github.com/search?q=repo%3Areactjs%2Fja.react.dev%20%E3%83%87%E3%83%95%E3%82%A9%E3%83%AB%E3%83%88%E5%80%A4&type=code) よりも[初期値](https://github.com/search?q=repo%3Areactjs%2Fja.react.dev+%E5%88%9D%E6%9C%9F%E5%80%A4&type=code) の方が多そうだったため、初期値に寄せています。

2023-07-16 07:52 UTC, jp-knj commented on src/content/reference/react/useContext.md
> +コンテクストプロバイダをネストすることで、情報を「累積」することができます。ここの例では、`Section` コンポーネントはセクションのネストの深さを指定する `LevelContext` を追跡しています。親セクションから `LevelContext` を読み取り、その数値に 1 を加えた `LevelContext` を子に提供します。その結果、`Heading` コンポーネントは自動的に
> 情報を「累積」することができます。

蓄積か累積かで迷いました。

2023-07-18 12:10 UTC, smikitky requested changes
レビューの確認をお願いします。申し訳ないですが大多数の訳文に suggestion が入っています。

2023-07-18 14:15 UTC, jp-knj commented on src/content/reference/react/useContext.md
> +### フォールバックの初期値の指定 {/*specifying-a-fallback-default-value*/}
なるほどです、ありがとうございます。

2023-07-18 14:18 UTC, jp-knj commented on src/content/reference/react/useContext.md
> +コンテクストプロバイダをネストすることで、情報を「累積」することができます。ここの例では、`Section` コンポーネントはセクションのネストの深さを指定する `LevelContext` を追跡しています。親セクションから `LevelContext` を読み取り、その数値に 1 を加えた `LevelContext` を子に提供します。その結果、`Heading` コンポーネントは自動的に
補足説明、ありがとうございます:pray:

2023-07-18 14:23 UTC, jp-knj commented on src/content/reference/react/useContext.md
> +* `SomeContext`: 事前に [`createContext`](/reference/react/createContext) で作成したコンテクストになります。コンテクスト自体が情報を保持しているわけではなく、コンポーネントから提供したり、読み取ったりできるような情報を表しています。
kind of を人やものを指して「～ような」を翻訳してしまいました。
種別の方が意味が分かり易くて、良いと思います:pray:

2023-07-18 14:25 UTC, jp-knj commented on src/content/reference/react/useContext.md
> +`useContext` は、呼び出したコンポーネントのコンテクスト値を返します。コンポーネントがツリー内で呼び出されるとき、その上位に位置する最も近い `SomeContext.Provider` に渡された `value` として決定されます。そのようなプロバイダが存在しない場合は、返り値はそのコンテクストの [`createContext`](/reference/react/create
そうですね、コンポーネントが変化するのは、state や props (今回だとコンテクストの現在値)が変化したときでしたね。

2023-07-18 14:42 UTC, jp-knj commented on src/content/reference/react/useContext.md
> +コンテクストを `Button` に渡すために、該当のコンテクストプロバイダでラップします :
申し訳ないです:pray:

2023-07-18 14:49 UTC, jp-knj commented on src/content/reference/react/useContext.md
> +### コンテクストを介したデータの更新 {/*updating-data-passed-via-context*/}
"介した"と"経由" は実は迷ったのですが、この違いを言語化できていませんでした。ありがとうございます。

2023-07-18 14:52 UTC, jp-knj commented on src/content/reference/react/useContext.md
> +#### コンテクストを介して値を更新する {/*updating-a-value-via-context*/}
なんとなく、わかった気がします...

2023-07-18 14:56 UTC, jp-knj commented on src/content/reference/react/useContext.md
> +この例では、2 つの独立したコンテクストがあります。`CurrentUserContext` は現在のユーザを表すオブジェクトを保持している間、`ThemeContext` を文字列として現在のテーマを提供します
勘違いしていました、ありがとうございます。

2023-07-18 15:02 UTC, jp-knj commented on src/content/reference/react/useContext.md
> +アプリが大きくなると、アプリのルートに近くにコンテクストの「ピラミッド」ができるかもしれません。何も問題はないです。ですが、入れ子になった見た目が気に入らないなら、プロバイダを単一のコンポーネントに抽出することができます。この例では、`MyProviders` は「配管」を隠蔽し、渡された子のプロバイダーを必要なプロバイダーの中にレンダーします。`theme` と `setTheme` の st
> 「theme と setTheme の state」

たしかに、そうですね。セッタは state ではないですね。

> "piece of state" は[不可算名詞である state を無理矢理数える](https://shinuwakaeng.com/uncountable-count-piece)ために使われているもの

これは、初めて知りました。ありがとうございます。

2023-07-18 15:06 UTC, jp-knj commented on src/content/reference/react/useContext.md
> +大規模なアプリでは、コンテクストと [reducer](/reference/react/useReducer) を組み合わせて、コンポーネントから状態に関連するロジックを抽出するのが一般的です。この例では、すべての「配線」は `TasksContext.js` に隠蔽されており、リデューサと 2 つの分離したコンテクストが含まれています。
既出の単語だったんですね、検索してませんでした。
ありがとうございます:pray:

2023-07-18 15:09 UTC, jp-knj commented on src/content/reference/react/useContext.md
> +初期値は**絶対に変更されません**。コンテクストを更新したいなら、[上記で説明したように](#updating-data-passed-via-context)、state と一緒に使用します。
@smikitky 
if, when が出てきたときにどうやって日本語で伝わりやすい表現にするか、いつも迷っています。

2023-07-18 15:13 UTC, jp-knj commented on src/content/reference/react/useContext.md
> +### ツリーにある一部のコンテクストを上書きする {/*overriding-context-for-a-part-of-the-tree*/}
> a part of the tree 

そうですね...

2023-07-18 15:17 UTC, jp-knj commented on src/content/reference/react/useContext.md
> +#### 自動的にネストされた見出し {/*automatically-nested-headings*/}
この翻訳、いいですね！

2023-07-18 15:25 UTC, jp-knj commented on src/content/reference/react/useContext.md
> +### MyComponent はプロバイダからの値を見れません {/*my-component-doesnt-see-the-value-from-my-provider*/}
すいません、ありがとうございます。

2023-07-18 15:44 UTC, jp-knj commented
お手数、おかけして申し訳ございません 🙇
再度レビューお願いします。

2023-07-19 13:57 UTC, smikitky approved these changes
これで大丈夫です、ありがとうございました。

次回から "Files Changed" タブで "Add suggestion to batch" 機能を使うようお願いします。

「あとで rebase + force-push すればいい」と思われるかもしれませんが、毎サジェスチョンごとに GitHub 上でコミットを行うと、GitHub Actions や Vercel での再ビルド・再デプロイやバンドルの解析が毎回走ってしまい、そこそこの負荷になります。無料枠は 3000 分ほどはあるはずですが、全ての翻訳言語で共通のリソースなので、この言語のこの記事の翻訳だけで 100 分以上も CPU を使ってしまうのはよくありません。（まあ多少超えても Meta が払ってくれてるとは思うのですが）

2023-07-27 13:46 UTC, koba04 approved these changes
👍 レビュー遅くなりすみません、ありがとうございます！！

2023-07-27 13:46 UTC, merged