Translate "Fragment"
reactjs/ja.react.dev pull request #626
Opened 2023-07-16 16:19 UTC by jp-knj

2023-07-22 16:07 UTC, jp-knj commented on src/content/reference/react/Fragment.md
> -Use `Fragment`, or the equivalent `<>...</>` syntax, to group multiple elements together. You can use it to put multiple elements in any place where a single element can go. For example, a component
> where a single element can go.

単一の要素が行き来できる場所 と訳しましたが、あまり確信を持ってておりません。

2023-07-22 16:07 UTC, jp-knj commented on src/content/reference/react/Fragment.md
> -- React does not [reset state](/learn/preserving-and-resetting-state) when you go from rendering `<><Child /></>` to `[<Child />]` or back, or when you go from rendering `<><Child /></>` to `<Child /
`when you go from rendering ~ to ~ or back`

~ から ~ に変更したとき と訳しましたが、意図通りに訳しているのか、確信を持てておりません。妙案がございましたら、宜しくお願いいたします

他にも `single level deep` を１つ分の階層の深さと訳すか迷いました。

2023-07-23 19:36 UTC, smikitky requested changes
読みやすさのために直訳から外した部分と、逆に直訳に近づけた部分があります。ご確認ください。

2023-07-23 19:36 UTC, smikitky commented on src/content/reference/react/Fragment.md
> +上述の例は、React から `Fragment` をインポートすることと同じです：
```suggestion
上述の例は、React から `Fragment` をインポートして以下のように書くことと同じです。
```

分かりづらくならないよう補いました

2023-07-23 19:36 UTC, smikitky commented on src/content/reference/react/Fragment.md
> +`Fragment` を使うとテキストとコンポーネントを一度にグループ化することができます：
```suggestion
`Fragment` を使うとテキストとコンポーネントをグループ化することができます：
```

together を訳出するなら「まとめて」「一緒に」あたりだと思います。
1 回でやるか 2 回に分けてやるかの話ではないので「一度に」は不適切かなと。

2023-07-23 19:38 UTC, smikitky commented
[Files Changed](https://github.com/reactjs/ja.react.dev/pull/626/files) のタブから "Add suggestion to batch" をつかってまとめてコミットをお願いします。

2023-07-23 23:29 UTC, jp-knj reviewed
suggestion の追加

2023-07-23 23:51 UTC, smikitky approved these changes
ありがとうございました！

2023-08-04 13:30 UTC, koba04 approved these changes
👍 ありがとうございます！！

2023-08-04 13:31 UTC, merged