Translate built-in React APIs
reactjs/ja.react.dev pull request #636
Opened 2023-07-19 15:12 UTC by natsuokawai

2023-07-19 16:35 UTC, smikitky requested changes
ありがとうございます。小さなスタイルの問題などに関する対応をお願いします。

2023-07-19 16:35 UTC, smikitky commented on src/content/reference/react/apis.md
> +[フック](/reference/react) や [コンポーネント](/reference/react/components) の他に、`react` パッケージはコンポーネントの定義に役立つ他の API も提供しています。このページでは、残りのモダンな React API をすべてリストアップしています。
```suggestion
[フック](/reference/react)や[コンポーネント](/reference/react/components)の他に、`react` パッケージはコンポーネントの定義に役立つ他の API も提供しています。このページでは、残りのモダンな React API をすべてリストアップしています。
```

2023-07-19 16:35 UTC, smikitky commented on src/content/reference/react/apis.md
> +* [`memo`](/reference/react/memo) を利用すると、同じ props を持つコンポーネントの再レンダーをスキップできます。[`useMemo`](/reference/react/useMemo) と [`useCallback`](/reference/react/useCallback) と一緒に使用されます。
```suggestion
* [`memo`](/reference/react/memo) を利用すると、同じ props を持つコンポーネントの再レンダーをスキップできます。[`useMemo`](/reference/react/useMemo) や [`useCallback`](/reference/react/useCallback) と一緒に使用されます。
```

2023-07-19 16:35 UTC, smikitky commented on src/content/reference/react/apis.md
> +* [`startTransition`](/reference/react/startTransition) を使うと、state の更新を非緊急としてマークできます。[`useTransition`](/reference/react/useTransition) に似ています。
```suggestion
* [`startTransition`](/reference/react/startTransition) を使うと、state の更新を低緊急度 (non-urgent) としてマークできます。[`useTransition`](/reference/react/useTransition) に似ています。
```

https://github.com/reactjs/ja.react.dev/pull/628/files と用語を統一させてください。

2023-07-20 00:31 UTC, smikitky approved these changes
ありがとうございます！

2023-08-22 06:43 UTC, koba04 approved these changes
👍 レビュー遅くなりすみません、ありがとうございます！

2023-08-22 06:43 UTC, merged