Translate createContext
reactjs/ja.react.dev pull request #638
Opened 2023-07-19 16:34 UTC by natsuokawai

2023-07-20 02:20 UTC, smikitky approved these changes
ほとんどは訳語統一やフォーマット関連です。ご確認をお願いします。

2023-07-20 02:20 UTC, smikitky commented on src/content/reference/react/createContext.md
> +* `value`: プロバイダ内のコンテクストを読み取るコンポーネントに渡したい値です。どんなに深くても構いません。コンテクストの値は任意の型にすることができます。プロバイダ内で `useContext(SomeContext)` を呼び出しているコンポーネントは、それより上位の最も内側の対応するコンテクストプロバイダの `value` を受け取ります。
```suggestion
* `value`: このプロバイダの内側（深さに関わらず）にあるコンポーネントがコンテクストを読み取る際に、渡したい値です。コンテクストの値は任意の型にすることができます。プロバイダ内で `useContext(SomeContext)` を呼び出しているコンポーネントは、それより上位かつ最も内側にある対応するコンテクストプロバイダの `value` を受け取ります。
```

「どんなに深くても構いません」を別の文に分けると「value を指定する深さ(?)」の話をしているように見えてしまいそうです

2023-07-20 02:20 UTC, smikitky commented on src/content/reference/react/createContext.md
> +コンテクストを利用することで、明示的に props を渡さずに、コンポーネントに深くまで [情報を渡す](/learn/passing-data-deeply-with-context)ことができます。
```suggestion
コンテクストを利用することで、明示的に props を渡さずに、コンポーネントに深くまで[情報を渡す](/learn/passing-data-deeply-with-context)ことができます。
```

2023-07-20 02:20 UTC, smikitky commented on src/content/reference/react/createContext.md
> +`createContext` は <CodeStep step={1}>コンテクストオブジェクト</CodeStep> を返します。それを `useContext()` に渡すことで、コンポーネントからコンテクストを読み取ることができます：
```suggestion
`createContext` は<CodeStep step={1}>コンテクストオブジェクト</CodeStep>を返します。それを `useContext()` に渡すことで、コンポーネントからコンテクストを読み取ることができます：
```

2023-07-20 02:20 UTC, smikitky commented on src/content/reference/react/createContext.md
> +デフォルトでは、コンポーネントが受け取る値は、コンテクストを作成するときに指定した <CodeStep step={3}>デフォルトの値</CodeStep> になります。しかし、デフォルトの値は決して変わらないため、これ自体では役に立ちませんね。
```suggestion
デフォルトでは、コンポーネントが受け取る値は、コンテクストを作成するときに指定した<CodeStep step={3}>デフォルトの値</CodeStep>になります。しかし、デフォルトの値は決して変わらないため、これ自体では役に立ちませんね。
```

2023-07-20 02:20 UTC, smikitky commented on src/content/reference/react/createContext.md
> +これで、`Page` コンポーネントとその内部のすべてのコンポーネントは、どんなに深くても、渡されたコンテクストの値を "見る" ことができます。渡されたコンテクストの値が変更されると、React はコンテクストを読み取るコンポーネントを再レンダーします。
```suggestion
これで、`Page` コンポーネントとその内部のすべてのコンポーネントは、どんなに深くても、渡されたコンテクストの値を「見る」ことができます。渡されたコンテクストの値が変更されると、React はコンテクストを読み取るコンポーネントを再レンダーします。
```

2023-07-20 02:20 UTC, smikitky commented on src/content/reference/react/createContext.md
> +[コンテクストの読み取りと提供、例についてさらに読む。](/reference/react/useContext)
```suggestion
[コンテクストの読み取りと提供、例についてさらに読む](/reference/react/useContext)
```

2023-07-20 02:20 UTC, smikitky commented on src/content/reference/react/createContext.md
> +異なるファイルにあるコンポーネントが同じコンテクストにアクセスする必要があることがよくあります。これが、別のファイルでコンテクストを宣言することが一般的な理由です。他のファイルでコンテクストを利用できるようにするために、[`export` 文](https://developer.mozilla.org/en-US/docs/web/javascript/reference/statements
```suggestion
異なるファイルにあるコンポーネントが同じコンテクストにアクセスする必要があることがよくあります。そのため、一般的には別ファイルでコンテクストを宣言します。他のファイルでコンテクストを利用できるようにするために、[`export` 文](https://developer.mozilla.org/en-US/docs/web/javascript/reference/statements/export)を使用できます：
```

2023-07-20 02:20 UTC, smikitky commented on src/content/reference/react/createContext.md
> +これは [コンポーネントのインポートとエクスポート](/learn/importing-and-exporting-components)と同様に動作します。
```suggestion
これは[コンポーネントのインポートとエクスポート](/learn/importing-and-exporting-components)と同様に動作します。
```

2023-07-20 02:20 UTC, smikitky commented on src/content/reference/react/createContext.md
> +このようなコードは *デフォルト* のコンテクストの値を指定します：
```suggestion

このようなコードは*デフォルト*のコンテクストの値を指定します：
```

元ファイルに空行が 2 つあるので合わせます

2023-07-20 02:20 UTC, smikitky requested changes
間違って approve してしまったので request changes し直します

2023-07-20 04:03 UTC, natsuokawai commented
レビューありがとうございます。スタイルの指摘を多くさせてしまいすみません。

2023-07-20 06:13 UTC, smikitky requested changes
1 箇所修正漏れがあるようですので対応をお願いします。

2023-07-20 06:13 UTC, smikitky commented on src/content/reference/react/createContext.md
> +* `defaultValue`: コンポーネントがコンテクストを読み取るときに、その上のツリー内で対応するコンテクストプロバイダがない場合にコンテクストが持つ値です。デフォルト値が必要ない場合は `null` を指定します。デフォルト値は "最後の手段" として使われるように意図されています。これは静的な値であり、時間が経過しても変化しません。
```suggestion
* `defaultValue`: コンポーネントがコンテクストを読み取るときに、その上のツリー内で対応するコンテクストプロバイダがない場合にコンテクストが持つ値です。デフォルト値が必要ない場合は `null` を指定します。デフォルト値は「最後の手段」として使われるように意図されています。これは静的な値であり、時間が経過しても変化しません。
```

[引用符の扱いのルール](https://github.com/reactjs/ja.react.dev/wiki/%E7%BF%BB%E8%A8%B3%E3%82%B9%E3%82%BF%E3%82%A4%E3%83%AB%E3%82%AC%E3%82%A4%E3%83%89#%E5%BC%95%E7%94%A8%E7%AC%A6%E3%81%AE%E6%89%B1%E3%81%84)に従います

2023-07-20 09:37 UTC, smikitky approved these changes

2023-08-24 10:42 UTC, koba04 approved these changes
👍 ありがとうございます！！

2023-08-24 10:42 UTC, merged