Translate "<progress>" component
reactjs/ja.react.dev pull request #640
Opened 2023-07-22 04:57 UTC by natsuokawai

2023-07-22 05:01 UTC, natsuokawai commented on src/content/reference/react-dom/components/progress.md
> +進行状況のインジケータを表示するためには、[ブラウザ組み込みの `<progress>` コンポーネント](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/progress)をレンダーします。
7行目では
```
[built-in browser `<progress>` component]
```
23行目では
```
[built-in browser `<progress>`] component
```
と揺れがありますが、どちらも同じURLなので、翻訳verではどちらも
```
[ブラウザ組み込みの `<progress>` コンポーネント]
```
と、`コンポーネント`をリンクテキストに含む形にしています。

2023-07-23 19:59 UTC, smikitky requested changes
"indeterminate" の訳語のみ対応をお願いします。

2023-07-23 19:59 UTC, smikitky commented on src/content/reference/react-dom/components/progress.md
> +* [`value`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/progress#attr-value)： `0` から `max` までの数値、または `null`（進行状況が不確定なことを表す）。完了した量を指定します。
```suggestion
* [`value`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/progress#attr-value)： `0` から `max` までの数値、または進行状況が不定 (indeterminate) であることを表す `null`。完了した量を指定します。
```

[MDN に丁寧な訳があり](https://developer.mozilla.org/ja/docs/Web/HTML/Element/progress)、そちらが「不定」になっていますので合わせてよいと思います。

2023-07-23 19:59 UTC, smikitky commented on src/content/reference/react-dom/components/progress.md
> +進行中でない場合、進行状況のインジケータを不確定な状態にするために `value={null}` を渡します。
```suggestion
進行状況のインジケータを不定状態にするには `value={null}` を渡します。
```

"If the operation is not ongoing" の部分はどうしましょう…。本来 null は「ongoing ではあるけど具体的な進行割合が計算できない」場合に使うものであって「ongoing ではない」場合に使うものではないと思うのですが…。9 割方原文の間違いだと思うのでしれっと無視するのもアリだと思いますし、原文通りの妙な説明を残すのもやむを得ないかもしれませんし、「操作の進行状況を表示できない場合」とかを入れて訳したことにしてもいいかもしれません。お任せします。

2023-07-27 15:15 UTC, natsuokawai commented on src/content/reference/react-dom/components/progress.md
> +進行中でない場合、進行状況のインジケータを不確定な状態にするために `value={null}` を渡します。
ありがとうございます。確かに（https://html.spec.whatwg.org/#the-progress-element も見たりしましたが）進行中でない場合とは言っていないですね。suggestしていただいた役を採用します

2023-07-30 02:40 UTC, smikitky approved these changes
ありがとうございました！

2023-08-24 10:45 UTC, koba04 approved these changes
👍 ありがとうございます！！！

2023-08-24 10:45 UTC, merged