Translate "useReducer"
reactjs/ja.react.dev pull request #641
Opened 2023-07-23 03:14 UTC by locol23

2023-08-03 12:16 UTC, smikitky requested changes
ひとまず用語統一をお願いしてよいでしょうか。

- 状態 → state
- レンダリング → レンダー
- action → アクション

2023-08-03 12:16 UTC, smikitky commented on src/content/reference/react/useReducer.md
>  #### Returns {/*returns*/}
「返り値」にしてください

2023-08-04 05:46 UTC, locol23 commented on src/content/reference/react/useReducer.md
>  #### Returns {/*returns*/}
申し訳ありません。修正しました 🙇

2023-08-04 05:48 UTC, locol23 commented
@smikitky
レビューありがとうございます。
用語について統一できておらず、申し訳ありませんでした。
修正しましたので、お手隙の際にご確認をお願いできないでしょうか 🙏

2023-08-08 06:55 UTC, smikitky requested changes
確認しました。スタイルの問題や読みやすさ向上のための小さな提案が主になりますが、対応をお願いいただけますでしょうか。

2023-08-08 06:55 UTC, smikitky commented on src/content/reference/react/useReducer.md
> +* **オプション** `init`: 初期 state を返す初期化関数です。指定されていない場合、初期 state は `initialArg` に設定されます。そうでない場合、初期 state は `init(initialArg)` の結果が設定されます。
```suggestion
* **省略可能** `init`: 初期 state を返す初期化関数です。指定されていない場合、初期 state は `initialArg` そのものになります。指定されている場合、初期 state は `init(initialArg)` の結果になります。
```

2023-08-09 12:45 UTC, locol23 commented
@smikitky 丁寧に見て頂き、suggestion ありがとうございました 🙏 修正しましたので、お手隙の際にご確認をお願いできないでしょうか 🙇

2023-08-09 13:43 UTC, smikitky commented
すみません、一度に表示されていないだけで他にも指摘事項があるのでご確認いただけますでしょうか。↓のような感じで隠れているはずです。

<img width="547" alt="image" src="https://github.com/reactjs/ja.react.dev/assets/7779406/60c21ff2-5ac1-44b0-8625-d54e0b5c3d48">

2023-08-09 14:24 UTC, locol23 commented on src/content/reference/react/useReducer.md
> +* `dispatch` 関数は、**次のレンダーのための state 変数のみを更新**します。`dispatch` 関数を呼び出した後に state 変数を読み取ると、呼び出し前の古い値が返されます。([古い state の値が表示される](#ive-dispatched-an-action-but-logging-gives-me-the-old-state-value))
@smikitky 確かにその通りです。suggestion ありがとうございます 🙇

2023-08-09 14:35 UTC, locol23 commented on src/content/reference/react/useReducer.md
> +* 与えられた新しい値が、[`Object.is`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/is) の比較により、現在の `state` と同じと判断された場合、React は**コンポーネントとその子要素の再レンダーをスキップ**します。これは最適化です。R
@smikitky どう訳すか悩んだ部分だったので、綺麗に訳されていて納得です！

2023-08-09 14:56 UTC, locol23 commented on src/content/reference/react/useReducer.md
> +既存の `state` オブジェクトを変更して返しているため、React は更新を無視します。これを修正するには、常に [state 内のオブジェクトを更新する](/learn/updating-objects-in-state)ことと、[state 内の配列を更新する](/learn/updating-arrays-in-state)ことを確実にする必要があります：
@smikitky ありがとうございます！わかりやすくなったと思います！

2023-08-09 14:59 UTC, locol23 commented on src/content/reference/react/useReducer.md
> +ステートが予期せず `undefined` になる場合、おそらくいずれかの `case` で state を `return` し忘れているか、アクションのタイプがいずれの `case` とも一致していない可能性があります。原因を見つけるために、`switch` の外でエラーをスローしてください。
@smikitky ありがとうございます 🙇

2023-08-09 15:06 UTC, locol23 commented
@smikitky 大変失礼いたしました 🙇 隠れているレビューについても確認し、修正しましたので、お手隙の際にご確認をお願いできないでしょうか 🙏

2023-08-10 02:05 UTC, smikitky approved these changes
ありがとうございました！

2023-08-11 10:15 UTC, locol23 commented
@smikitky 丁寧に見て頂きありがとうございました！

2023-08-26 14:05 UTC, koba04 approved these changes
👍 ありがとうございます！！！

2023-08-26 14:05 UTC, merged