Translate "useMemo"
reactjs/ja.react.dev pull request #643
Opened 2023-07-26 14:42 UTC by yuta-ike

"useMemo" の翻訳です

2023-08-02 09:28 UTC, smikitky requested changes
遅くなりましたがこちらの確認をお願いします。コード内のコメントは翻訳しないことにしています。

また、先に言っておくべきだったかもしれないのですが、[useCallback](https://ja.react.dev/reference/react/useCallback) とかなり翻訳が被っているところがあるのですが、とりあえず独立してレビューしました。ゆくゆくは統一を行うべきだとは思いますが、ぱっと見た感じ文ごとに「この文はこっちの訳の方が自然だな」みたいな感じです。もし余裕があれば見比べていただいて統一を試みていただければ幸いです（useCallback 側の翻訳に手を入れても構いません）。

2023-08-02 09:28 UTC, smikitky commented on src/content/reference/react/useMemo.md
> +### コンポーネントがレンダーされるたびに、`useMemo` 内の関数が再実行される {/*every-time-my-component-renders-the-calculation-in-usememo-re-runs*/}
```suggestion
### コンポーネントがレンダーされるたびに `useMemo` 内の関数が再実行される {/*every-time-my-component-renders-the-calculation-in-usememo-re-runs*/}
```

2023-08-02 09:28 UTC, smikitky commented on src/content/reference/react/useMemo.md
> +あるいは、`useMemo` を削除し、`Report` 自体を [`memo`](/reference/react/memo) でラップすることでも解決できます。`item` props が変化しない場合は、`Report` の再レンダーはスキップされ、`Chart` の再レンダーもスキップされます。
```suggestion
あるいは、`useMemo` を削除し、`Report` 自体を [`memo`](/reference/react/memo) でラップすることでも解決できます。`item` が変化しない場合は、`Report` の再レンダーはスキップされ、`Chart` の再レンダーもスキップされます。
```

2023-08-02 09:28 UTC, smikitky commented on src/content/reference/react/useMemo.md
> +1. [state を更新する不要なエフェクト](/learn/you-might-not-need-an-effect)を避けてください。React アプリのパフォーマンス問題のほとんどは、エフェクトから発生する更新の連鎖によって引き起こされます。この連鎖によって、コンポーネントを何度も繰り返しレンダーさせてしまうのです。
```suggestion
1. [state を更新する不要なエフェクト](/learn/you-might-not-need-an-effect)を避けてください。React アプリのパフォーマンス問題のほとんどは、エフェクト内での連鎖的な state 更新によってコンポーネントのレンダーが何度も引き起こされるために生じます。
```

2023-08-02 09:28 UTC, smikitky commented on src/content/reference/react/useMemo.md
> +この例でも、`List` の実装には**あえて遅延が入っています**。そのため、レンダー中に呼び出している React コンポーネントが著しく遅い場合の挙動を確認できます。タブを変更したり、テーマを切り替えたりしてみてください。
```suggestion
この例でも、`List` の実装には**人為的な遅延が入っています**。そのため、レンダー中に呼び出している React コンポーネントが著しく遅い場合の挙動を確認できます。タブを変更したり、テーマを切り替えたりしてみてください。
```

2023-09-13 03:45 UTC, smikitky commented
@yuta-ike こちら対応願えますでしょうか。時間が厳しいようでしたら仰っていただければ、このままこちらで引き継ぐことも可能です。

2023-09-20 04:51 UTC, smikitky commented
@yuta-ike 主要記事で翻訳未完了がこれのみとなっており、これが完了しないと[サイト全体がGoogle検索でひっかからない](https://github.com/reactjs/ja.react.dev/issues/667)という残念なことになっています。

- そちらで速やかにレビューコメントに対応していただく
- suggestion をこちらで適用してこのまま進める
- この PR を close してこちらでやり直す

いずれでも構いませんので判断をお願いします。

2023-09-20 05:27 UTC, yuta-ike commented
@smikitky 申し訳ございません！完全に失念しておりました。今修正に取り掛かります。ご迷惑おかけしてすみません

2023-09-25 04:03 UTC, smikitky requested changes

2023-09-25 04:04 UTC, smikitky approved these changes

2023-09-25 04:05 UTC, smikitky commented
ありがとうございました！
明らかなミスが2箇所あったのでこちらで修正させていただきました。

2023-09-27 03:18 UTC, smikitky commented
@yuta-ike まだ `memo` の方のドキュメントは着手されていませんよね。私の方で引き取って良いでしょうか。

2023-09-27 07:04 UTC, yuta-ike commented
@smikitky すみません、お願い致します

2023-10-10 02:14 UTC, smikitky commented
@koba04 こちらのレビューをお願いします！

2023-10-11 15:43 UTC, koba04 approved these changes
👍 LGTM!!!

2023-10-11 15:43 UTC, merged