Translate "<select>" component
reactjs/ja.react.dev pull request #644
Opened 2023-07-27 00:18 UTC by ainoshment

`react-dom: Components` の `<select>` の翻訳です。

2023-07-27 03:15 UTC, ainoshment commented on src/content/reference/react-dom/components/select.md
> +* `children`: `<select>` は [`<option>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/option)、[`<optgroup>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/optgroup)、[`<datalis
[`<datalist>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/optgroup) のリンク先が間違っていましたが、修正はしていません。

2023-08-02 10:21 UTC, smikitky requested changes
幾つかの修正と、読みやすくするための suggestion を行いましたので確認をお願いします。

2023-08-02 10:21 UTC, smikitky commented on src/content/reference/react-dom/components/select.md
> +***制御された*セレクトボックスをレンダーするには、`value` プロパティを渡してください。**React はセレクトボックスに常に渡した `value` を保持します。通常、[state 変数](/reference/react/useState)を宣言することでセレクトボックスを制御します。
```suggestion
***制御された*セレクトボックスをレンダーするには、`value` プロパティを渡してください**。React はセレクトボックスが常に渡した `value` を反映するようにします。通常、[state 変数](/reference/react/useState)を宣言することでセレクトボックスを制御します。
```

2023-08-02 10:21 UTC, smikitky commented on src/content/reference/react-dom/components/select.md
> +**`onChange` を指定せずに `value` を渡すと、オプションを選択することができなくなります。**セレクトボックスに `value` 渡して制御すると、渡した値が常に*強制*されることになります。したがって、state 変数を `value` として渡しても、`onChange` イベントハンドラ内でその state 変数を同期的に更新するのを忘れた場合、React はキーストロ
```suggestion
**`onChange` を指定せずに `value` を渡すと、オプションを選択することができなくなります。**セレクトボックスに `value` を渡して制御を行うと、渡した値でセレクトボックスを*強制的に固定*することになります。したがって、state 変数を `value` として渡しても、`onChange` イベントハンドラ内でその state 変数を同期的に更新するのを忘れた場合、React はセレクトボックスを、キーストローク毎に指定した `value` に戻してしまいます。
```

2023-08-02 10:21 UTC, smikitky commented on src/content/reference/react-dom/components/select.md
> +* [`required`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select#attr-required): ブーリアン。`true` の場合、フォームを送信するには値の指定が必要です。
```suggestion
* [`required`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select#attr-required): ブーリアン。`true` の場合、フォームを送信する際に値の指定を必須にします。
```

2023-08-02 10:21 UTC, smikitky commented on src/content/reference/react-dom/components/select.md
> +- セレクトボックスは同時に制御されたコンポーネントと非制御コンポーネントにはなれません。
```suggestion
- セレクトボックスは制御されたコンポーネントと非制御コンポーネントに同時になることはできません。
```

2023-08-02 10:21 UTC, smikitky commented on src/content/reference/react-dom/components/select.md
> +もし `<label>` 内に `<select>` をネストできない場合は、同じ ID を `<select id>` と [`<label htmlFor>`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLLabelElement/htmlFor) に渡すことで関連付けることができます。同一コンポーネントの複数のインスタンス間で競
```suggestion
もし `<label>` 内に `<select>` をネストできない場合は、同じ ID を `<select id>` と [`<label htmlFor>`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLLabelElement/htmlFor) に渡すことで関連付けることができます。同一コンポーネントの複数のインスタンス間での競合を避けるために、[`useId`](/reference/react/useId) を使用してそのような ID を生成することが推奨されます。
```

2023-08-02 10:21 UTC, smikitky commented on src/content/reference/react-dom/components/select.md
> +デフォルトでは、`<form>` 内の*どんな* `<button>` もフォームを送信します。これは予想外の挙動かもしれません！ 独自のカスタム `Button` React コンポーネントを利用している場合は、`<button>` の代わりに [`<button type="button">`](https://developer.mozilla.org/en-US/docs/Web/HTM
```suggestion
デフォルトでは、`<form>` 内の*あらゆる* `<button>` はフォームの送信を行います。これは予想外の挙動かもしれません！ 独自のカスタム `Button` React コンポーネントを利用している場合は、`<button>` の代わりに [`<button type="button">`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/button) を返すようにすることを考慮してください。そしてフォームを送信することが*意図されている*ボタンには明示的に `<button type="submit">` を使用してください。
```

2023-08-06 03:00 UTC, ainoshment commented
@smikitky （修正箇所が多くて😓）お手数をおかけしました...！修正を行いましたのでご確認よろしくお願いします！

2023-08-08 07:16 UTC, smikitky approved these changes

2023-08-08 07:17 UTC, smikitky commented
ありがとうございました。1箇所だけスタイルの問題を追加で修正させていただきました(3a4613cb987f8b33d7db13163c583df3b2acf957)。

2023-08-27 15:09 UTC, koba04 requested changes
@ainoshment
レビューありがとうございます！一点、Markdown フォーマットの修正だけ提案したので確認お願いします！

2023-08-27 15:09 UTC, koba04 commented on src/content/reference/react-dom/components/select.md
> +**`onChange` を指定せずに `value` を渡すと、オプションを選択することができなくなります。**セレクトボックスに `value` を渡して制御を行うと、渡した値でセレクトボックスを*強制的に固定*することになります。したがって、state 変数を `value` として渡しても、`onChange` イベントハンドラ内でその state 変数を同期的に更新するのを忘れた場合、
Markdown のフォーマットが崩れていたので修正です。

<img width="763" alt="image" src="https://github.com/reactjs/ja.react.dev/assets/250407/93c4a7ed-841b-4489-b542-b180b44760b6">


```suggestion
**`onChange` を指定せずに `value` を渡すと、オプションを選択することができなくなります。** セレクトボックスに `value` を渡して制御を行うと、渡した値でセレクトボックスを*強制的に固定*することになります。したがって、state 変数を `value` として渡しても、`onChange` イベントハンドラ内でその state 変数を同期的に更新するのを忘れた場合、React はセレクトボックスを、キーストローク毎に指定した `value` に戻してしまいます。
```

2023-08-27 16:00 UTC, smikitky commented on src/content/reference/react-dom/components/select.md
> +**`onChange` を指定せずに `value` を渡すと、オプションを選択することができなくなります。**セレクトボックスに `value` を渡して制御を行うと、渡した値でセレクトボックスを*強制的に固定*することになります。したがって、state 変数を `value` として渡しても、`onChange` イベントハンドラ内でその state 変数を同期的に更新するのを忘れた場合、
```suggestion
**`onChange` を指定せずに `value` を渡すと、オプションを選択することができなくなります**。セレクトボックスに `value` を渡して制御を行うと、渡した値でセレクトボックスを*強制的に固定*することになります。したがって、state 変数を `value` として渡しても、`onChange` イベントハンドラ内でその state 変数を同期的に更新するのを忘れた場合、React はセレクトボックスを、キーストローク毎に指定した `value` に戻してしまいます。
```

koba04さんの提案のように半角スペースを入れると今度は Textlint が「余計なところにスペースを入れるな」怒ってきますので、こちらでお願いします。

2023-08-27 19:05 UTC, smikitky commented on src/content/reference/react-dom/components/select.md
> +**`onChange` を指定せずに `value` を渡すと、オプションを選択することができなくなります。**セレクトボックスに `value` を渡して制御を行うと、渡した値でセレクトボックスを*強制的に固定*することになります。したがって、state 変数を `value` として渡しても、`onChange` イベントハンドラ内でその state 変数を同期的に更新するのを忘れた場合、
こちらでコミットしました

2023-08-28 01:27 UTC, koba04 approved these changes
👍

2023-08-28 01:27 UTC, merged