Translate "hydrate"
reactjs/ja.react.dev pull request #653
Opened 2023-08-16 13:52 UTC by riku929hr

`react-dom: APIs` の `hydrate` の翻訳を行いました。

行ったことは以下です。

- ChatGPT Markdown Translator での翻訳
- [スタイルガイド](https://github.com/reactjs/ja.react.dev/wiki/%E7%BF%BB%E8%A8%B3%E3%82%B9%E3%82%BF%E3%82%A4%E3%83%AB%E3%82%AC%E3%82%A4%E3%83%89)、[訳語の統一](https://github.com/reactjs/ja.react.dev/wiki/%E8%A8%B3%E8%AA%9E%E3%81%AE%E7%B5%B1%E4%B8%80) に沿った修正
- 元の英文と比較し、できる限り自然な日本語に修正

[こちら](https://github.com/reactjs/ja.react.dev/issues/452#issuecomment-1675971127) で宣言しておりましたが、もし先にご対応されているようでしたら、閉じていただいて構いません。

よろしくお願いいたします。

2023-08-20 12:48 UTC, smikitky requested changes
ありがとうございます。レビューを行いましたので確認をお願いします。

2023-08-20 12:48 UTC, smikitky commented on src/content/reference/react-dom/hydrate.md
> +* `reactNode`: 既存の HTML をレンダーするのに使用される「React ノード」。これは通常、React 17 における `ReactDOM Server` のメソッド（例：`renderToString(<App />)`）でレンダーされた JSX の一部である`<App />`のようなものです。
```suggestion
* `reactNode`: HTML を事前レンダーするのに使用された「React ノード」。これは通常、React 17 における `ReactDOM Server` のメソッド（例：`renderToString(<App />)`）でレンダーされた JSX である `<App />` のようなものです。
```

この "piece of" は英文法的に必要なゴミみたいなものですので日本語では訳さないでいいかなと思います

2023-08-20 12:48 UTC, smikitky commented on src/content/reference/react-dom/hydrate.md
> +* `domNode`: サーバー上でルート要素としてレンダーされた [DOM 要素](https://developer.mozilla.org/en-US/docs/Web/API/Element)。
```suggestion
* `domNode`: サーバ上でルート要素としてレンダーされた [DOM 要素](https://developer.mozilla.org/en-US/docs/Web/API/Element)。
```

2023-08-20 12:48 UTC, smikitky commented on src/content/reference/react-dom/hydrate.md
> +* **省略可能**: `callback`: 関数。渡された場合、React はコンポーネントのハイドレーション後にそれを呼び出します。
```suggestion
* **省略可能** `callback`: 関数。渡された場合、React はコンポーネントのハイドレーション後にそれを呼び出します。
```

1 つめのコロンは明らかに誤字なので削除しました

2023-08-20 12:48 UTC, smikitky commented on src/content/reference/react-dom/hydrate.md
> +* `hydrate` は、レンダーされたコンテンツが、サーバーでレンダーされたコンテンツと同一であることを期待しています。React はテキストコンテンツの差異を修正できますが、不一致はバグとして扱い修正する必要があります。
```suggestion
* `hydrate` は、レンダーされたコンテンツが、サーバでレンダーされたコンテンツと同一であることを期待しています。React はテキストコンテンツの差異を修正できますが、不一致はバグとして扱い修正する必要があります。
```

2023-08-20 12:48 UTC, smikitky commented on src/content/reference/react-dom/hydrate.md
> +* HTML が既にレンダーされていないクライアントレンダリングの場合、`hydrate()` はサポートされていません。代わりに、React 17 以前では [render()](/reference/react-dom/render)、React 18 以降では [createRoot()](/reference/react-dom/client/createRoot) を使用してください。
```suggestion
* アプリがクライアントレンダリングであり事前レンダーされた HTML がない場合、`hydrate()` はサポートされません。代わりに、React 17 以前では [render()](/reference/react-dom/render)、React 18 以降では [createRoot()](/reference/react-dom/client/createRoot) を使用してください。
```

2023-08-20 12:48 UTC, smikitky commented on src/content/reference/react-dom/hydrate.md
> +サーバとクライアントで意図的に異なるものをレンダーする必要がある場合、2 回のレンダーを行うことができます。クライアントで異なるものをレンダーするコンポーネントは、以下の `isClient` のような [state 変数](/reference/react/useState)を読み取ることができます。この変数は、[effect](/reference/react/useEffect) 内で `
```suggestion
サーバとクライアントで意図的に異なるものをレンダーする必要がある場合、2 回に分けたレンダーを行うことができます。クライアントで異なるものをレンダーするコンポーネントは、`isClient` のような [state 変数](/reference/react/useState)を読み取るようにし、この変数を[エフェクト](/reference/react/useEffect)内で `true` に設定することができます。
```

2023-08-20 12:48 UTC, smikitky commented on src/content/reference/react-dom/hydrate.md
> +この方法では、初回のレンダーはサーバと同じコンテンツをレンダーし、不一致を回避しますが、追加のパスがハイドレーションの直後に同期的に行われます。
```suggestion
この方法では、初回のレンダーはサーバと同じコンテンツをレンダーし、不一致を回避しますが、追加のレンダーがハイドレーションの直後に同期的に行われます。
```

"multi-pass" とかの pass は結構訳しづらいので置き換えていいと思います…

2023-08-20 12:48 UTC, smikitky commented on src/content/reference/react-dom/hydrate.md
> +React で完全に構築されたアプリでは、**通常、アプリ全体の起動時に 1 つの「ルート」を一度だけハイドレートします**。
```suggestion
React で完全に構築されたアプリでは、**通常、アプリ全体の起動時に 1 つの「ルート」のハイドレーションを一度だけ行います**。
```

用語統一のためです

2023-08-20 12:48 UTC, smikitky commented on src/content/reference/react-dom/hydrate.md
> +サーバーとクライアントの間で、単一の要素の属性やテキストコンテンツがやむを得ない理由で異なる場合（たとえば、タイムスタンプなど）、ハイドレーションの不一致警告を抑制することができます。
```suggestion
サーバとクライアントの間で、単一の要素の属性やテキストコンテンツがやむを得ない理由で異なる場合（たとえば、タイムスタンプなど）、ハイドレーションの不一致警告を抑制することができます。
```

2023-08-22 05:45 UTC, smikitky requested changes
すみません、前指摘したものに関して幾つか修正残しがあるようです。
加えて新たに気付いた問題もいくつかあり、対応願えますでしょうか。

2023-08-22 05:45 UTC, smikitky commented on src/content/reference/react-dom/hydrate.md
> +React は、`domNode` 内に存在する HTML にアタッチし、その内部の DOM を管理します。React で完全に構築されたアプリには、ルートコンポーネントを引数にした `hydrate` 呼び出しが通常 1 つのみ存在します。
```suggestion
React は、`domNode` 内に存在する HTML にアタッチし、その内部の DOM を管理を引き継ぎます。React で完全に構築されたアプリには、ルートコンポーネントを引数にした `hydrate` 呼び出しが通常 1 つのみ存在します。
```

2023-08-22 05:45 UTC, smikitky commented on src/content/reference/react-dom/hydrate.md
> +* `reactNode`: 既存の HTML をレンダーするのに使用される「React ノード」。これは通常、React 17 における `ReactDOM Server` のメソッド（例：`renderToString(<App />)`）でレンダーされた JSX のである`<App />`のようなものです。
```suggestion
* `reactNode`: 既存の HTML をレンダーするのに使用される "React ノード"。これは通常、`ReactDOM Server` のメソッド（例：React 17 の `renderToString(<App />)`）でレンダーされた JSX である`<App />`のようなものです。
```

2023-08-22 05:45 UTC, smikitky commented on src/content/reference/react-dom/hydrate.md
> +[さらに例を読む](#usage)
```suggestion
[さらに例を見る](#usage)
```

2023-08-23 02:26 UTC, smikitky approved these changes

2023-08-23 02:27 UTC, smikitky commented
3 箇所 suggestion が残っていたのでこちらでコミットさせていただきました。(cfadc24ae21b9f8ffce40187761ba857aaa4d557)

2023-08-23 05:10 UTC, riku929hr commented
すみません、ありがとうございました🙇

2023-08-27 07:54 UTC, smikitky commented on src/content/reference/react-dom/hydrate.md
> +このアプローチではコンポーネントを 2 回レンダーする必要があるためハイドレーションが遅くなります。低速な接続の場合、ユーザ体験に注意してください。JavaScript コードは初期レンダーされた HTML よりもかなり遅く読み込まれる場合があるため、ハイドレーション直後に異なる UI をレンダーするとユーザに不快感を与えるかもしれません。
```suggestion
このアプローチではコンポーネントを 2 回レンダーする必要があるためハイドレーションが遅くなります。低速な接続におけるユーザ体験に注意してください。JavaScript コードは初期レンダーされた HTML よりもかなり遅く読み込まれる場合があるため、ハイドレーション直後に異なる UI をレンダーするとユーザに不快感を与えるかもしれません。
```

2023-08-27 07:54 UTC, smikitky commented on src/content/reference/react-dom/hydrate.md
> +* `reactNode`: 既存の HTML をレンダーするのに使用される "React ノード"。これは通常、`ReactDOM Server` のメソッド（例：React 17 の `renderToString(<App />)`）でレンダーされた JSX である`<App />`のようなものです。
```suggestion
* `reactNode`: 既存の初期 HTML をレンダーするのに使用された "React ノード"。これは通常、`ReactDOM Server` のメソッド（例：React 17 の `renderToString(<App />)`）でレンダーされた JSX、例えば `<App />` になります。
```

2023-09-04 07:14 UTC, koba04 approved these changes
👍 ありがとうございます！！！

2023-09-04 07:14 UTC, merged

2023-10-13 06:00 UTC, smikitky commented on src/content/reference/react-dom/hydrate.md
> +* `reactNode`: 既存の HTML をレンダーするのに使用される「React ノード」。これは通常、React 17 における `ReactDOM Server` のメソッド（例：`renderToString(<App />)`）でレンダーされた JSX の一部である`<App />`のようなものです。
@riku929hr 偶然[これ](https://blog.riku929hr.com/entry/20230916/1694848362)を見つけたのでお答えしますと、この "piece of" は英語で不可算名詞を無理やり数えるときの表現です。受験英語的には "a piece of paper", "a piece of information" が有名だと思います。React ドキュメントの場合 JSX や state は不可算名詞扱いなので、「ひと固まりの JSX」「複数の state ではなく 1 個の state」などと言いたい文脈で "piece of" がよく出てきます。日本語の場合、無理やり "JSX 素片" などとすることもできるとは思いますが、単に無視するのが最も楽かな、ということでした。

- https://oluolu-english.com/how-to-count/
- https://www.qqeng.com/blog2/study/15514.html