Translate "findDOMNode"
reactjs/ja.react.dev pull request #670
Opened 2023-08-27 12:49 UTC by jp-knj

2023-08-30 16:46 UTC, jp-knj commented on src/content/reference/react-dom/findDOMNode.md
> +この API は、今後のメジャーバージョンの React で削除される予定です。[代替案を見る](#alternatives)
"This API will be removed in a future major version of React." は複数のファイルで散見される文言のため、[Translate "hydrate"](https://github.com/reactjs/ja.react.dev/pull/653/files#diff-fcb75f0cd87651e93d9fcac72e656f7645566f4977f9696508f994a5e469dd07R7) を参考に翻訳

別 PR の場合だと、 "この API は、将来の React のメジャーバージョンで削除されます。" と翻訳されていました。
▼ 該当 PR
- https://github.com/reactjs/ja.react.dev/pull/660/files#diff-48328e91812704c8ff16795c8482e08bdf2062505536b4d154f7d43b2b910d91R7
- https://github.com/reactjs/ja.react.dev/pull/653/files#diff-fcb75f0cd87651e93d9fcac72e656f7645566f4977f9696508f994a5e469dd07R7

2023-08-30 16:46 UTC, jp-knj commented on src/content/reference/react-dom/findDOMNode.md
> +* `findDOMNode` はマウントされたコンポーネント（つまり、DOM に配置されたコンポーネント）でのみ動作します。まだマウントされていないコンポーネント内から `findDOMNode` を呼び出そうとすると（まだ作成されていないコンポーネントの `render()` 内から `findDOMNode()` を呼び出そうとするのと同様に）、例外がスローされます。
"If you try to call this on a component that has not been mounted yet" の ”this” は、`findDOMNode` を指していると考えて、"this" を直訳せずに `findDOMNode` と置き換えて、翻訳しました。

”this” を訳さないでも良いのかなとも考えたのですが、どう翻訳しましょうか

2023-08-30 16:58 UTC, smikitky commented on src/content/reference/react-dom/findDOMNode.md
> +* `findDOMNode` はマウントされたコンポーネント（つまり、DOM に配置されたコンポーネント）でのみ動作します。まだマウントされていないコンポーネント内から `findDOMNode` を呼び出そうとすると（まだ作成されていないコンポーネントの `render()` 内から `findDOMNode()` を呼び出そうとするのと同様に）、例外がスローされます。
日本語では主語や目的語の省略はごく普通なので、理解に問題ないのであれば適当にやっていただいて大丈夫です。

この like は「例えば」と訳してもいいかなと思います。

2023-08-31 00:10 UTC, jp-knj commented on src/content/reference/react-dom/findDOMNode.md
> +この API は、今後のメジャーバージョンの React で削除される予定です。[代替案を見る](#alternatives)
分かりました、ありがとうございます。

2023-08-31 00:11 UTC, jp-knj commented on src/content/reference/react-dom/findDOMNode.md
> +* `findDOMNode` はマウントされたコンポーネント（つまり、DOM に配置されたコンポーネント）でのみ動作します。まだマウントされていないコンポーネント内から `findDOMNode` を呼び出そうとすると（まだ作成されていないコンポーネントの `render()` 内から `findDOMNode()` を呼び出そうとするのと同様に）、例外がスローされます。
なるほど、ありがとうございます。

2023-09-13 03:44 UTC, smikitky requested changes
遅くなり申し訳ありません。確認・対応をお願いします。

2023-09-13 03:44 UTC, smikitky commented on src/content/reference/react-dom/findDOMNode.md
> +`findDOMNode` は、指定された `componentInstance` に最も近いブラウザ DOM ノードを返します。コンポーネントが `null` をレンダーする場合や `false` をレンダーする場合、`findDOMNode` は `null` を返します。コンポーネントが文字列をレンダーする場合は `findDOMNode` は値を含むテキスト DOM ノードを返します。
```suggestion
`findDOMNode` は、指定された `componentInstance` 内で最も上位にあるブラウザ DOM ノードを返します。コンポーネントが `null` をレンダーする場合や `false` をレンダーする場合、`findDOMNode` は `null` を返します。コンポーネントが文字列をレンダーする場合は `findDOMNode` はその値を含んでいるテキスト DOM ノードを返します。
```

"first closest browser DOM node" は原文の時点で割と意味不明なので意図を汲んで意訳しておきましょう…

2023-09-13 03:44 UTC, smikitky commented on src/content/reference/react-dom/findDOMNode.md
> +### ref からコンポーネントの独自の DOM ノードを読み取る {/*reading-components-own-dom-node-from-a-ref*/}
```suggestion
### ref でコンポーネント自身の DOM ノードを読み取る {/*reading-components-own-dom-node-from-a-ref*/}
```

この own は独自性の話ではなく「他コンポーネントに属するものではなく自分のもの」の意味で使われています

2023-09-14 11:22 UTC, jp-knj commented on src/content/reference/react-dom/findDOMNode.md
> +`findDOMNode` を使用しているコードは壊れやすいです。なぜなら JSX ノードと対応する DOM ノードを操作するコード間の接続が明示的でないためです。例えば、この `<input />` を `<div>` でラップしてみてください。
> 形容詞 + です は[稚拙に感じる人もまだ多い](https://mohritaroh.hateblo.jp/entry/2019/08/16/090000)ので避けましょう

 初めて知りました、ありがとうございます

2023-09-14 11:23 UTC, jp-knj commented on src/content/reference/react-dom/findDOMNode.md
> +クラスコンポーネントがないモダンな React では、代わりに [`useRef`](/reference/react/useRef) を呼び出した同等のコードになります。
あー、ケアできていませんでした

2023-09-14 11:28 UTC, jp-knj commented on src/content/reference/react-dom/findDOMNode.md
> +`findDOMNode` は、指定された `componentInstance` に最も近いブラウザ DOM ノードを返します。コンポーネントが `null` をレンダーする場合や `false` をレンダーする場合、`findDOMNode` は `null` を返します。コンポーネントが文字列をレンダーする場合は `findDOMNode` は値を含むテキスト DOM ノードを返します。
なるほど、ありがとうございます 🙏🏿

2023-09-14 11:34 UTC, jp-knj commented
"Files Changed" タブで "Add suggestion to batch" しました、確認お願いします

2023-09-14 14:39 UTC, smikitky approved these changes
ありがとうございます！

2023-09-18 14:58 UTC, koba04 approved these changes
👍 ありがとうございます！！！

2023-09-18 14:58 UTC, merged