Translate "cache"
reactjs/ja.react.dev pull request #696
Opened 2023-09-29 14:04 UTC by locol23

2023-10-05 18:47 UTC, locol23 commented on src/content/reference/react/cache.md
> -When rendering `Profile`, we call <CodeStep step={2}>`getUser`</CodeStep> again. If the initial <CodeStep step={1}>`getUser`</CodeStep> call has already returned and cached the user data, when when `
`when when` となっている部分はおそらくミスだと思うので、本家の方に PR を出そうと思います！

2023-10-05 19:13 UTC, locol23 commented
@smikitky 
お待たせしてすみません。お手隙の際にレビューをお願いできないでしょうか 🙏

2023-10-09 09:03 UTC, locol23 commented on src/content/reference/react/cache.md
> -When rendering `Profile`, we call <CodeStep step={2}>`getUser`</CodeStep> again. If the initial <CodeStep step={1}>`getUser`</CodeStep> call has already returned and cached the user data, when when `
PR 出しました！
https://github.com/reactjs/react.dev/pull/6344

2023-10-10 08:23 UTC, smikitky requested changes
レビューをしましたので確認をよろしくお願いします。

2023-10-10 08:23 UTC, smikitky commented on src/content/reference/react/cache.md
> +<CodeStep step={3}>非同期レンダー</CodeStep> はサーバコンポーネントでのみサポートされています。
```suggestion
<CodeStep step={3}>非同期レンダー</CodeStep>はサーバコンポーネントでのみサポートされています。
```

2023-10-10 08:23 UTC, smikitky commented on src/content/reference/react/cache.md
> +長時間実行されるデータ取得をキャッシュすることで、コンポーネントのレンダー前に非同期処理を開始することができます。
```suggestion
時間のかかるデータ取得をキャッシュすることで、コンポーネントのレンダー前に非同期処理を開始することができます。
```

2023-10-10 08:23 UTC, smikitky commented on src/content/reference/react/cache.md
> +この例では、非同期関数 <CodeStep step={1}>`fetchData`</CodeStep> は `fetch` を待っている Promise を返します。
```suggestion
この例では、非同期関数 <CodeStep step={1}>`fetchData`</CodeStep> は `fetch` 結果を待機するプロミスを返します。
```

2023-10-10 08:23 UTC, smikitky commented on src/content/reference/react/cache.md
> +最初の <CodeStep step={2}>`getData`</CodeStep> 呼び出しでは、<CodeStep step={1}>`fetchData`</CodeStep> から返された Promise がキャッシュされます。その後のキャッシュ探索では、同じ Promise が返されます。
```suggestion
最初の <CodeStep step={2}>`getData`</CodeStep> 呼び出しでは、<CodeStep step={1}>`fetchData`</CodeStep> から返されたプロミスがキャッシュされます。その後のキャッシュ探索では、同じプロミスが返されます。
```

2023-10-11 14:37 UTC, locol23 commented on src/content/reference/react/cache.md
> +キャッシュを持つバージョンの関数を作成するために、コンポーネントの外部で `cache` を呼び出します。
横断的に見ていないとわからない部分のため、表記統一ありがとうございます 🙏

2023-10-11 16:08 UTC, locol23 commented on src/content/reference/react/cache.md
> +[非同期関数](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function) を評価するとき、その処理の [Promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_O
承知しました 🙏

2023-10-11 23:41 UTC, locol23 commented on src/content/reference/react/cache.md
> +キャッシュヒットを最大化し、処理を減らすためには、2 つのコンポーネントは同じメモ化された関数を呼び出して同じキャッシュにアクセスするべきです。寧ろ、専用のモジュールでメモ化された関数を定義し、コンポーネント間で [`インポート`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/impor
ありがとうございます。言われてみればその通りです。 `Instead,` の部分の翻訳をどうするかに意識がもっていかれていました 🙏

2023-10-11 23:47 UTC, locol23 commented on src/content/reference/react/cache.md
> +上記の例では、<CodeStep step={2}>`Precipitation`</CodeStep> と <CodeStep step={1}>`Temperature`</CodeStep> はそれぞれ `cache` を呼び出して、それぞれ独自のキャッシュの索引を持つ新しいメモ化された関数を作成します。両方のコンポーネントが同じ `cityData` でレンダーする場合、それぞれが `c
look-up をどう訳すか四苦八苦していたので、 `キャッシュテーブル` はわかりやすくてしっくりきました！

2023-10-11 23:52 UTC, locol23 commented on src/content/reference/react/cache.md
> +与えられた引数で `cachedFn` を呼び出すと、まずキャッシュにキャッシュされた結果が存在するかどうかを確認します。キャッシュされた結果が存在する場合、その結果を返します。存在しない場合、引数で `fn` を呼び出し、結果をキャッシュに保存し、その結果を返します。`fn` が呼び出されるのはキャッシュミスが発生したときだけです。
了解です 💦

2023-10-12 00:43 UTC, locol23 commented on src/content/reference/react/cache.md
> +<CodeStep step={3}>2回目の呼び出し</CodeStep> までに Promise がまだ _pending_ の場合、`await` は結果を待ちます。`fetch` を待っている間に React が計算作業を続けることができるため、<CodeStep step={3}>2回目の呼び出し</CodeStep> の待ち時間を短縮することが最適化になります。
@smikitky 読み直してみて、読んだ人が作業ってなんだろうとなるかもと思ったため、 `計算作業`を`計算処理`へ変更した方がわかりやすくなりそうに感じたのですが、いかがでしょうか 🙇

2023-10-12 00:44 UTC, locol23 commented on src/content/reference/react/cache.md
> +##### コンポーネントの外部でメモ化された関数を呼び出すと、キャッシュは使用されません。{/*pitfall-memoized-call-outside-component*/}
ありがとうございます 🙇 違和感ありません 🙏

2023-10-12 00:53 UTC, locol23 commented on src/content/reference/react/cache.md
> +Promise がすでに解決している場合、エラーまたは _fulfilled_ の結果になると、`await` はその値をすぐに返します。どちらの結果でも、パフォーマンスの利点があります。
リンクと MDN の定義ありがとうございます 🙏 「履行」は自分も聞き慣れないため、「正常終了」でいいと思います！

2023-10-12 00:59 UTC, locol23 commented on src/content/reference/react/cache.md
> +しかし、`useMemo` は `App` が再レンダーされ、`record` オブジェクトが変わらない場合、各コンポーネントインスタンスは処理をスキップし、`avgTemp` のメモ化された値を使用します。`useMemo` は、与えられた依存関係で `avgTemp` の最後の計算のみをキャッシュします。
承知しました 🙏

2023-10-12 04:26 UTC, smikitky commented on src/content/reference/react/cache.md
> +`Page` をレンダーするとき、コンポーネントは <CodeStep step={1}>`getUser`</CodeStep> を呼び出しますが、返されたデータは使用しません。この早期の <CodeStep step={1}>`getUser`</CodeStep> 呼び出しは、`Page` が他の計算処理を行い、子をレンダーしている間に非同期のデータベースクエリを開始します。
ごめんなさい、単なるタイプミスです、仰る通りです

2023-10-12 04:28 UTC, smikitky commented on src/content/reference/react/cache.md
> +<CodeStep step={3}>2回目の呼び出し</CodeStep> までに Promise がまだ _pending_ の場合、`await` は結果を待ちます。`fetch` を待っている間に React が計算作業を続けることができるため、<CodeStep step={3}>2回目の呼び出し</CodeStep> の待ち時間を短縮することが最適化になります。
はい、計算処理で大丈夫です

2023-10-12 04:32 UTC, smikitky commented
初期状態で隠れているレビューコメントを全部表示するのを忘れているようで、幾つかのレビューコメントに対応されていないようですので対応をお願いします。

また[こちら](https://github.com/reactjs/ja.react.dev/wiki/Git%E4%BD%9C%E6%A5%AD%E3%81%AE%E3%83%92%E3%83%B3%E3%83%88#github-%E4%B8%8A%E3%81%A7%E3%81%AE%E3%82%B5%E3%82%B8%E3%82%A7%E3%82%B9%E3%83%81%E3%83%A7%E3%83%B3%E3%81%AE%E3%83%90%E3%83%83%E3%83%81%E9%81%A9%E7%94%A8)の点についてもよろしくお願いします。

2023-10-12 04:41 UTC, locol23 commented
@smikitky すみません。まだ確認途中でした 🙏 残りのレビューコメントも確認します 🙇 また、バッチについて承知しました。対応します。

2023-10-12 04:49 UTC, locol23 commented on src/content/reference/react/cache.md
> +上記のいずれも該当しない場合、Reactがキャッシュに存在するかどうかをチェックする方法に問題があるかもしれません。
なるほどです。ありがとうございます。

2023-10-12 05:00 UTC, locol23 commented on src/content/reference/react/cache.md
> +これを解決する一つの方法は、ベクトルの次元を `calculateNorm` に渡すことです。これは次元自体がプリミティブであるため、機能します。
確かに、次元だから 3 と勘違いしてもおかしくないですね...。本来の意図を汲んだ訳で了解です！

2023-10-12 05:15 UTC, locol23 commented on src/content/reference/react/cache.md
> +`Page` をレンダーするとき、コンポーネントは <CodeStep step={1}>`getUser`</CodeStep> を呼び出しますが、返されたデータは使用しません。この早期の <CodeStep step={1}>`getUser`</CodeStep> 呼び出しは、`Page` が他の計算処理を行い、子をレンダーしている間に非同期のデータベースクエリを開始します。
確認ありがとうございます！修正します！

2023-10-12 05:16 UTC, locol23 commented on src/content/reference/react/cache.md
> +<CodeStep step={3}>2回目の呼び出し</CodeStep> までに Promise がまだ _pending_ の場合、`await` は結果を待ちます。`fetch` を待っている間に React が計算作業を続けることができるため、<CodeStep step={3}>2回目の呼び出し</CodeStep> の待ち時間を短縮することが最適化になります。
確認ありがとうございます！修正します！

2023-10-12 05:24 UTC, locol23 commented
@smikitky 残っていたレビューコメントの反映と、提案し、確認して頂いた 2 点の修正が完了しましたので、お手すきでご確認をお願いできないでしょうか 🙇 

■ 確認して頂いた 2 点
1. https://github.com/reactjs/ja.react.dev/pull/696#discussion_r1351364954
2. https://github.com/reactjs/ja.react.dev/pull/696#discussion_r1351285942

[上記 2 点を修正したコミット](https://github.com/reactjs/ja.react.dev/pull/696/commits/f484a2492dab3628a3490fa7bcfc315f5760763c)

2023-10-12 09:26 UTC, smikitky approved these changes
ありがとうございました！
一部微修正させていただきました。

2023-10-12 10:09 UTC, locol23 commented
@smikitky こちらこそ、丁寧に見て頂いてありがとうございました！微修正もありがとうございます 🙏

2023-10-12 15:14 UTC, koba04 approved these changes
👍 ありがとうございます！

2023-10-12 15:14 UTC, merged